RustCrypto/crypto-bigint

src/uint/bits.rs

Replaces a while loop with a bit-counting intrinsic

Use `Inner::leading_zeros` to compute `UInt::bits`

---

src/lib.rs
src/non_zero.rs

Adds a generic wrapper type for any `T` which impls `Integer`, which ensures that the inner value is non-zero.

Add `NonZero` wrapper

---

src/uint/div.rs

Implement `Div` & `Rem` for `UInt`  with `NonZero`

---

src/non_zero.rs

Adds convenience functions to convert `core::num::NonZeroUx` to `NonZero<UInt<LIMBS>>`.

Add conversion `core::num::NonZeroUx`

---

src/array.rs
src/traits.rs

I could add more traits if this makes sense. Improves situations like https://github.com/RustCrypto/password-hashes/pull/232/files#r712984411.

Add traits to `ArrayDecoding`

---

src/limb/add.rs
src/limb/mul.rs
src/limb/sub.rs
src/traits.rs
src/uint/add.rs
src/uint/div.rs
src/uint/mul.rs
src/uint/rand.rs
src/uint/sqrt.rs
src/uint/sub.rs
src/uint/sub_mod.rs

Adds the following traits:
- `CheckedAdd`
- `CheckedSub`
- `CheckedMul`
Also changes the existing inherent methods to use the traits.

`Checked*` traits

---

src/lib.rs

Makes it simple to import traits used by this crate

Add `prelude` module

---

src/limb/add.rs
src/limb/mul.rs
src/limb/sub.rs
src/uint/add.rs
src/uint/mul.rs
src/uint/sub.rs

Adds the following saturating arithmetic operations to `UInt`:
- `saturating_add`
- `saturating_sub`
- `saturating_mul`

Add `saturating_*` ops

---

src/uint.rs

Adds a `const fn` for borrowing the limbs of a `UInt` as a reference to an array of word-sized integers (i.e. `LimbUInt`).
The intended use case is passing this array as an argument to `const fn` fiat-crypto functions.

crypto-bigint: add `UInt::as_uint_array`

---

src/limb/encoding.rs
tests/proptests.rs

Add `Encoding` tests

---

src/uint/modular/constant_mod.rs
src/uint/modular/runtime_mod.rs

- add `DynResidue::zero()` (unfortunately a constant is not possible, so it takes `DynResidueParams`)
- add `Residue::ZERO`
- impl `ConstantTimeEq`, `Default`, and `Zero` for `Residue`

Zeroes for residues

---

.github/workflows/crypto-bigint.yml
benches/bench.rs

- Fixed some compilation errors forgotten in #141 
- Added benchmark building to CI to prevent that from happening again (just building, not running, to save time)

Fix benchmarks compilation

---

src/limb/rand.rs
src/uint/rand.rs

Superseding #50 
- Rebased
- Fixed a bug in `Limb::random_mod()`
- Small style fixes

Faster random_mod

---

src/uint/array.rs

Need for `elliptic-curves` implementations

Impl `ArrayEncoding` for U224/U544

---

src/uint/encoding.rs

The general `crypto-bigint` convention is that the things are constant-time, unless explicitly marked otherwise. This PR makes `from_be/le_hex()` constant-time using a constant-time decoding snippet from the `base16ct` crate.
Alternatives to this approach:
- `base16ct` could be possibly used directly, but the high-level functions there take a mutable reference and therefore cannot be `const`. One could expose `base16ct::decode_nibble()`, or perhaps add a variant of functions operating on arrays. 
- We could just mark `from_be/le_hex()` as vartime
Also, should there be non-panicking `from_be/le_hex()` variants that would return an error instead, for more convenient use in runtime contexts? (Edit: this is actually handled by #247)

Make `Uint::from_be_hex()` and `from_le_hex()` constant-time

---

src/uint/modular/runtime_mod.rs

Implements `ConditionallySelectable` and `ConstantTimeEq` for `DynResidue` and `DynResidueParams`

Add `subtle` trait impls for `DynResidue` and `DynResidueParams`

---

src/uint/bits.rs

Add remark for bits() method documentation.

vartime remark

---

.github/workflows/crypto-bigint.yml

CI: add `minimal-versions` check

---

src/uint/boxed/ct.rs

Some were previously named `cond_*` instead

BoxedUint: rename `conditional_*` methods for consistency

---

src/modular/boxed_residue/mul.rs

Always performs `sub_vv` on the lower half of the output, and conditionally assigns `upper` to `lower` using `subtle`.
It doesn't matter if we unconditionally subtract, since the output will be overwritten in the case where it's "unnecessary" (but actually necessary for constant-time operation).
There are still some data-dependent branches, however, which have been annotated with a TODO.

Eliminate some timing variability in `montgomery_mul`

---

src/limb/cmp.rs

Uses the `ConditionallySelectable` impl on `Ordering` to simplify the implementation.

Limb: simplify `Ord` impl

---

src/modular/boxed_residue/mul.rs

Uses constant-time comparisons instead of variable-time ones.
This does not appear to impact performance.
```
time:   [24.423 ms 24.441 ms 24.460 ms]
change: [-0.1437% -0.0327% +0.0751%] (p = 0.56 > 0.05)
No change in performance detected.
```

BoxedUint: fix a constant-time TODO in `montgomery_mul`

---

src/modular/boxed_residue/mul.rs

Partially reverts changes from #409

Restore preconditions check in montgomery_mul

---

src/modular/boxed_residue/pow.rs

Modular exponentiation of `BoxedResidue` is performed using "almost Montgomery multiplication" whose output is reduced to the bit size of the modulus, but not the modulus itself. This is fine for the intermediate values in the operation, which consist of a series of squarings/multiplies, but the final result needs to be fully reduced.
This is implemented by conditionally subtracting the modulus in constant-time.
A final debug assertion ensures the result is fully reduced.

BoxedResidue: ensure modpow results are fully reduced

---

benches/dyn_residue.rs

```
Montgomery arithmetic/invert, U256
time:   [5.1410 µs 5.1513 µs 5.1637 µs]
Montgomery arithmetic/Bernstein-Yang invert, U256
time:   [1.9483 µs 1.9645 µs 1.9863 µs]
```
A 2.6X improvement

DynResidue: preliminary Bernstein-Yang benchmarks

---

src/modular/bernstein_yang/boxed.rs

Makes them mutate their arguments "in place" (although internally they still do quite a few allocations).

BoxedBernsteinYangInverter: refactor `fg` and `de`

---

src/modular/bernstein_yang.rs

Renames from `Uint62L` since the underlying type is signed.

Bernstein-Yang: rename `Int62L`

---

src/modular/bernstein_yang.rs

This should make it easier to implement GCD

Bernstein-Yang: minor refactoring

---

src/uint/gcd.rs

Tests some edge cases which weren't tested before

Uint: expand GCD tests

---

Cargo.toml
benches/boxed_residue.rs
benches/residue.rs

Adds benchmarks for the `Residue` type, largely copy/pasted from `DynResidue`.

`Residue` benchmarks

---

src/modular/bernstein_yang.rs
src/modular/bernstein_yang/boxed.rs

- Extracts a `divsteps` function in both the stack-allocated and boxed implementations which can be reused for both inversions and GCD
- Changes the boxed implementation to use more in-place operations

Refactor Bernstein-Yang implementation(s)

---

src/odd.rs

Fix random `Odd` generation

---

src/uint/mul.rs

Wound up being pretty trivial to do.

Make `Uint::square` into a `const fn`

---

src/uint/mul.rs

Make `Uint::widening_mul` into a `const fn`

---

src/uint/rand.rs

A follow-up for #510. Handle the case of `bit_length = 0`.
An alternative here is to take a `NonZeroU32` parameter.

Add a proper handling of `bit_length = 0` in RandomBits

---

src/limb.rs
src/modular/bernstein_yang.rs
src/modular/bernstein_yang/boxed.rs

- Expand documentation on `Limb` representations
- Bernstein-Yang doc cleanups

Documentation improvements

---

src/uint.rs

Uses `cast()` to perform the pointer cast, which is much simpler, and fixes the `trivial_pointer_casts` lint.
Also adds tests.

Uint: simplify `as(_mut)_words` pointer casts

---

.github/workflows/crypto-bigint.yml
src/limb/encoding.rs
src/modular/bernstein_yang/boxed.rs

Should help identify potentially problematic unsafe code

CI: run tests under miri

---

src/odd.rs

Adjusting the test to account for Bincode allowing trailing bytes by default.
See the [Bincode documentation](https://docs.rs/bincode/1.3.3/bincode/config/index.html#options-struct-vs-bincode-functions) on this matter.
Fixes #605.
Cc @dvdplm and thank you for finding the issue.

Account for Bincode allowing trailing bytes by default

---

Cargo.lock
Cargo.toml

Now with even GCD support /cc @dignifiedquire

v0.6.0-rc.1

---

src/modular/bernstein_yang/boxed.rs

Similar to #628, changes `Int64L::is_negative` to return `Choice` rather than `bool`.
This eliminates some of the branching in the implementation (#627)

BoxedUint: constant-time Bernstein-Yang `is_negative`

---

src/uint/boxed/sub.rs

Adds `Sub` impls for `BoxedUint` for the following `rhs` types, similar to what #650 did for `Add`:
- `Uint<LIMBS>`
- `u8`
- `u16`
- `u32`
- `u64`
- `u128`
The primitive integer types convert to `Uint<LIMBS>` then leverate the `Sub` impl for that.

BoxedUint: `Sub` impls for stack allocated types

---

src/modular/boxed_monty_form.rs

This PR fixes broken `BoxedMontyForm` documentation.

Fix documentation

---

Cargo.lock
Cargo.toml
src/uint/encoding/der.rs

Bump `der` dependency to v0.8.0-rc.1

---

src/modular/const_monty_form/macros.rs

Add doc comment support to `impl_modulus!`

---

src/traits.rs

For symmetry with `Div` bounds.

Add `RemAssign` bound to `Integer`

---

Cargo.lock
Cargo.toml
src/uint/encoding/der.rs

See https://github.com/RustCrypto/crypto-bigint/issues/752

chore(deps): bump `der` from `0.7` to `0.8.0-rc.1`

---

Cargo.lock
Cargo.toml

Notably this includes a `rand_core` v0.9 upgrade

v0.7.0-pre.0

---

README.md

readme: new MSRV-aware resolver can handle patch releases

---

src/uint/boxed/add.rs
src/uint/boxed/sub.rs

Fixup assertion in AddAssign and SubAssign of BoxedUint

---

.github/workflows/crypto-bigint.yml
src/modular/monty_form/invert.rs

CI: add `typos` job

---

Cargo.lock
Cargo.toml

Release that includes the trimmed serialization API for the `rsa` crate

v0.7.0-pre.4

---

Cargo.lock
Cargo.toml
src/uint/boxed/encoding.rs
src/uint/boxed/encoding/serde.rs

Implement serde for BoxedUint

---

src/const_choice.rs
src/non_zero.rs

`NonZeroInt::new_unwrap`

---

src/modular/boxed_monty_form.rs
src/modular/monty_form.rs
src/traits.rs
src/uint/boxed/mul_mod.rs
src/uint/mul_mod.rs

Mostly convenience methods for now, although it might be possible to further optimize them later.

Add SquareMod trait and implement for Uint, BoxedUint

---

benches/uint.rs
src/modular/bingcd/extension.rs
src/modular/bingcd/gcd.rs
src/modular/bingcd/matrix.rs
src/modular/bingcd/xgcd.rs

This PR introduces the optimized binxgcd algorithm.
Supersedes https://github.com/RustCrypto/crypto-bigint/pull/761 and #856

Optimized Binary Extended GCD
