src/limb.rs, src/uint/bits.rs
We can eventually expose these as part of the public API, but I'd like to nitpick the names first.
I'd also like to immediately cut a release in order to update the repo location, so for now I'm removing these from the public API then we can add them back after some discussion.
cc @mikelodder7
=> Make `SignedWide` and `UInt::bits` visibility `pub(crate)`

proptests/tests/equivalence.rs, src/uint/cmp.rs, src/uint/div.rs
Div methods were taking a copy instead of a reference where the other arithmetic methods were taking a reference. This makes them identifical.
=> make div similar to other interfaces

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs
- `UInt::sqrt` ([#9])
- Make `UInt` division similar to other interfaces ([#8])
[#8]: https://github.com/RustCrypto/formats/pull/8
[#9]: https://github.com/RustCrypto/formats/pull/9
=> crypto-bigint v0.2.9

src/array.rs, src/lib.rs, src/uint.rs, src/uint/array.rs
As discussed on Zulip. Any improvements on the documentation are welcome.
=> Implement `ArrayDecoding`

src/array.rs, src/uint/array.rs
=> Rename `into_bigint_x` to `into_uint_x`

.github/workflows/crypto-bigint.yml, src/non_zero.rs
The recent `NonZero` addition broke builds with `default-features = false`. I will add CI checks too.
=> Fix build without `rand` crate feature

tests/proptests.rs
Hi @tarcieri 
I added `add_mod` test and `modulo` operation.
I changed the way to generate `random_mod` accordingly 😆
I would be grateful if you could confirm.
Thank you!
=> `add_mod` proptests

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, README.md, src/lib.rs, src/uint/div.rs
Bumps `edition = "2021"` and adds `rust-version = 1.56`.
This is the first in a set of breaking changes proposed in #20, and as such bumps the version to v0.3.0-pre (not for release).
=> Rust 2021 edition upgrade

src/uint/mul.rs
Fixes the inconsistency between `UInt::mul_wide` and `Limb::mul_wide` by reversing the order of the `UInt` version so it returns `(lo, hi)`.
This follows the "little endian" approach used in the rest of this crate for consistency.
Closes #4
=> Reverse ordering of `UInt::mul_wide` return tuple

src/limb.rs, src/non_zero.rs, src/traits.rs, src/uint.rs
Extracts a `Zero` trait from the `Integer` trait which contains only the associated `ZERO` constant and the `is_zero` method with a default implementation.
Changes the mandatory bound for `NonZero` to be the `Zero` trait rather than the much more restrictive `Integer`
This makes it possible to impl `Zero` on `Limb` even though it doesn't impl the full set of `Integer` traits, and therefore use `NonZero<Limb>`.
=> `Zero` trait

src/limb.rs, src/limb/add.rs, src/limb/bits.rs, src/limb/mul.rs, src/limb/rand.rs, src/limb/sub.rs, src/traits.rs, src/uint/bits.rs, src/uint/rand.rs, src/uint/sub_mod.rs
Changes the modulus for `random_mod` to be `NonZero`.
Changes the algorithm used by `random_mod` to generate a number that can be represented by the same number of bytes as the modulus.
Such a number can still be larger than the modulus, but is much more likely not to overflow than a "full-width" number provided the modulus is small relative to the width.
Closes #3 cc @Sc00bz
=> Fix `random_mod` performance for small moduli; `NonZero` moduli

src/wrapping.rs
...when the inner type impls `Zero`
=> Impl `Zero` for `Wrapping`

src/checked.rs, src/limb/add.rs, src/limb/mul.rs, src/limb/sub.rs, src/uint/add.rs, src/uint/mul.rs, src/uint/sub.rs
- Factor all `Checked` arithmetic into respective modules
- `Checked` support for `Limb`
- `Checked` support for reference types
=> `Checked` improvements

src/uint/div.rs
This prevents a potential panic condition if the `rhs` operand is zero by making it unrepresentable using the type system.
=> Have `Div` and `Rem` impls always take `NonZero` args

src/lib.rs, src/limb.rs, src/limb/add.rs, src/limb/bits.rs, src/limb/cmp.rs, src/limb/encoding.rs, src/limb/from.rs, src/limb/mul.rs, src/limb/rand.rs, src/limb/sub.rs, src/macros.rs, src/uint/bits.rs, src/uint/cmp.rs, src/uint/div.rs, src/uint/encoding.rs, src/uint/encoding/decoder.rs, src/uint/from.rs, src/uint/shl.rs, src/uint/shr.rs, src/uint/sqrt.rs
Also promotes `limb::BIT_SIZE` and `limb::BYTE_SIZE` to inherent constants of the `Limb` type.
=> Make `limb` module private; rename `limb::Inner` to `LimbUInt`

src/lib.rs, src/limb/from.rs, src/non_zero.rs, src/uint/bits.rs, src/uint/div.rs, src/uint/from.rs, src/uint/sqrt.rs, src/wrapping.rs
Adds a number of additional lints as a `#![warn(...)]` directive, including `trivial_numeric_casts`, which caught a number of redundancies.
=> Expand rustc lints

src/lib.rs
The replacement is: `Limb::BYTE_SIZE`
=> Remove deprecated `LIMB_BYTES` constant

.github/workflows/crypto-bigint.yml, Cargo.toml, src/checked.rs, src/lib.rs, src/limb.rs, src/limb/rand.rs, src/non_zero.rs, src/traits.rs, src/uint.rs, src/uint/rand.rs
Uses the new `doc = include_str!(...)` feature to include the README.md in the rustdoc.
Adds a "Usage" section to the rustdoc which gives a basic tour of the crate including the `UInt` type and various traits that operate on it.
=> Documentation improvements

src/limb/add.rs, src/limb/cmp.rs, src/limb/mul.rs, src/limb/sub.rs, src/traits.rs, src/uint.rs, src/uint/add.rs, src/uint/cmp.rs, src/uint/mul.rs, src/uint/sub.rs
Uses traits consistently for `is_zero`, `is_odd`, and `is_even`
=> Reduce number of inherent methods

src/traits.rs, src/uint/bit_and.rs, src/uint/bit_not.rs, src/uint/bit_or.rs, src/uint/bit_xor.rs
Adds the following bitwise operations:
- `BitAnd`
- `BitOr`
- `BitXor`
- `Shl`
- `Shr`
Additionally adds impls of the `Bit*` traits on `UInt<LIMBS>` directly, in addition to the existing impls on `Wrapping<UInt<LIMBS>>`.
This is safe because there is no difference between the "wrapping" or "checked" versions of these operations: they always succeed and there is no "wrapping" behavior to worry about.
This is debatably a breaking change but one that is extremely unlikely to cause any problems in practice, especially since `crypto-bigint` v0.3 was just released. To be on the safe side though, these changes will immediately be published in a v0.3.1 release, and the current v0.3.0 yanked so as to prevent any potential incompatibilities.
=> Add bitwise ops to `Integer` trait

src/non_zero.rs
The goal is to enable:
```rust
const P: NonZero<U256> = NonZero::from_uint(U256::from_be_hex(
"ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551",
));
```
Alternatively we can also provide `from_be_hex()` & co. methods on `NonZero` itself.
=> Implement const-friendly `NonZero` from `UInt`

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, README.md, src/lib.rs, src/nlimbs.rs, src/non_zero.rs, src/uint/div.rs, src/uint/encoding.rs, src/uint/encoding/decoder.rs, src/uint/from.rs
Replaces the previous `const_assert!` macro hack with a proper `assert!` leveraging the newly stabilized support for panicking in const contexts.
=> Use `const_panic`; MSRV 1.57

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, src/uint/encoding.rs, src/uint/encoding/der.rs
Adds support for decoding/encoding `UInt` as an ASN.1 DER `INTEGER`.
=> Add optional `der` feature

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, src/checked.rs, src/lib.rs, src/limb.rs, src/non_zero.rs, src/uint.rs, src/uint/macros.rs, src/wrapping.rs
Implemented `serde::Deserialize` and `serde::Serialize` for all types. This might be a bit overkill, implementing it for `UInt` might have been enough.
As serde currently doesn't support const generics (serde-rs/serde#1937), I used [serde-big-array](https://crates.io/crates/serde-big-array) for the `UInt` implementation. The dependency is quiet minimal, this PR also spawned est31/serde-big-array#14 to make sure that the dependency is as minimal as possible.
I hope the tests are appropriate enough.
=> Serde implementation

src/uint/add_mod.rs, src/uint/neg_mod.rs, src/uint/sub_mod.rs
The core implementations of these traits are already const generic, so there's no reason the trait impls shouldn't also be.
=> Use const generic impls of `*Mod` traits

.github/workflows/crypto-bigint.yml
The new MSRV for `cross` is 1.58.1.
However, rather than deal with that, this PR just removes the `cross` checks for MSRV 1.57.0 (i.e. `crypto-bigint` MSRV) and only runs `cross` on `stable`, which should simplify future maintenance.
=> CI: fix `cross` builds

src/lib.rs, src/limb.rs, src/limb/add.rs, src/limb/cmp.rs, src/limb/encoding.rs, src/limb/from.rs, src/limb/mul.rs, src/limb/sub.rs, src/uint.rs, src/uint/bits.rs, src/uint/cmp.rs, src/uint/div.rs, src/uint/encoding/decoder.rs, src/uint/from.rs, src/uint/shl.rs, src/uint/sqrt.rs
Also internally renames (Wide)`LimbUInt` => (Wide)`SignedWord`.
These names are slightly less unwieldy.
Note: breaking change.
=> Rename `LimbUInt` => `Word`, `WideLimbUInt` => `WideWord`

src/uint/from.rs
This is useful for clients who write generic code targeting both 32-bit and 64-bit.
=> uint: Implement from_word and from_wide_word

src/uint/neg_mod.rs
The new implementation uses 2 instead of 3 iterations over the limbs.
=> uint: Optimize neg_mod by simply calling sub_mod

src/uint/add_mod.rs, src/uint/sub_mod.rs
In some applications involving modulo arithmetic, there are occasions where one knows that a certain number `x` that needs to
be reduced is not much larger than the modulus `p`. In particular, if one knows `x < 2p`, one can simply reduce it by calling `x.sub_mod(&p, &p)`. This works due to the nature of the `sub_mod` implementation. However, it is currently unspecified behavior, as the documentation of `sub_mod` requires `x < p`.
This commit relaxes the requirement for `UInt::sub_mod` and analogously for `UInt::add_mod`, so that above-mentioned behavior doesn't change in a future update.
The traits `AddMod` and `SubMod` still have the original requirements, so one needs to call `UInt::add_mod` or `UInt::sub_mod` explicitly when relying on this behavior.
=> uint: Relax bounds for UInt::add_mod and UInt::sub_mod

src/limb/bit_and.rs
Previously, rustc didn't inline `Limb::bitand` inside functions such as `UInt::add_mod` and `UInt::sub_mod`, when calling them from a different crate. This is probably because non-generic functions without `inline` attribute don't get inlined across crates (unless using link-time optimization).
Here's the assembly that shows this:
<details>
<summary>Assembly generated for U256::sub_mod before this commit</summary>
```asm
crypto_bigint::uint::sub_mod::<impl crypto_bigint::uint::UInt<_>>::sub_mod:
push    rbp
push    r15
push    r14
push    r13
push    r12
push    rbx
push    rax
mov     r14, qword, ptr, [rsi]
sub     r14, qword, ptr, [rdx]
mov     eax, 0
sbb     rax, rax
mov     r15, qword, ptr, [rsi, +, 8]
sar     rax, 63
sub     r15, qword, ptr, [rdx, +, 8]
mov     ecx, 0
sbb     rcx, …
```
=> limb: always inline bitand

src/uint.rs, src/uint/add_mod.rs, src/uint/mul_mod.rs, src/uint/neg_mod.rs, src/uint/sub_mod.rs
For a project of mine where the modulus can be chosen to be close to `UInt::MAX`, I created optimized implementations of modular operations. I thought maybe others can benefit from them, too, so I ported my implementation to the crypto-bigint crate.
This commit implements modulo operations (`neg`, `add`, `sub`, `mul`) for special moduli that are so close to `MAX` that the difference to overflow fits in a single `Limb`. For such moduli, these new implementations are much faster than the existing generic modulus implementations. (For `mul` there's no comparison since there's no corresponding generic modulus implementation, yet.)
For `U256`, I benchmarked the generic against the specialized implementations using criterion-rs on Intel Core i7-8565U @ 1.80GHz and obtained the following average …
=> uint: Implement modulo operations for special moduli

src/uint/encoding.rs, src/uint/macros.rs
On this machine these changes take `Encoding::from_{le|be}_bytes` from around 200ns to around 3ns for a U256. It adds non-const (but still constant-time) methods for decoding UInts from a byte array.
Restricting the input to an array allows the assert to be optimized out, as is the `unreachable!()` panicking according to godbolt. But there may be a cleaner way to obtain the fixed-size chunks (for example, copying into an intermediate buffer), and in future `slice::as_chunks` could be applicable.
=> Faster decoding for UInt

src/limb.rs, src/limb/shl.rs, src/limb/shr.rs, src/uint/div.rs
Convenience methods to avoid wrapping and unwrapping the Limb.
=> Add left, right bitshift for Limb

src/uint/div.rs
=> Fix constant-time behaviour for ct_reduce/ct_div_rem

src/uint.rs
This is something I've found myself reaching for. It allows for `U256::LIMBS` (f.ex) to be used in a const context, instead of having to import the `nlimbs!` macro.
=> Add a public LIMBS constant to UInt

.github/dependabot.yml
Add Dependabot configuration to automatically open PRs for outdated actions.
Inspired by https://github.com/RustCrypto/hashes/pull/410#issuecomment-1252658128.
=> ci: add Dependabot configuration to keep GitHub Actions up to date

.github/workflows/crypto-bigint.yml, .github/workflows/security-audit.yml
Updates the actions [`actions/checkout`](https://github.com/actions/checkout) and [`actions/cache`](https://github.com/actions/cache) to v3, their latest major release.
This should basically be backwards compatible, so I expect no breakage.
=> ci: update actions used in GitHub Actions workflows

src/uint/neg_mod.rs
This change optimizes `neg_mod` (25% faster here) by performing a bit mask instead of `adc`.
=> Optimize neg_mod

src/uint/bits.rs, src/uint/div.rs, src/uint/rand.rs, src/uint/sqrt.rs
This adds `UInt::bit_vartime(index)` for accessing the value of the bit at a given index. It's trivial to cast the result to u8 or bool so I leave that up to the caller, to avoid casting the value twice.
For consistency and accuracy, `bits` is renamed to `bits_vartime`.
=> Add bit accessor methods

Cargo.lock, Cargo.toml, src/lib.rs, src/limb.rs, src/uint.rs, src/uint/bits.rs
Breaking changes were introduced in #130, so this bumps the crate's version to a prerelease to denote that. It will be bumped to `pre.0` for an actual crate release.
Also removes all deprecated APIs.
=> Bump version to `v0.5.0-pre`; remove deprecations

benches/bench.rs, src/limb/cmp.rs, src/uint/modular.rs, src/uint/modular/pow.rs, src/uint/modular/runtime_mod.rs, src/uint/modular/runtime_mod/runtime_pow.rs, tests/proptests.rs
- Made `pow_montgomery_form()` windowed; measured speedup is ~ 35us to 23.1us
- Added proptests for `pow()` and `pow_specific()` for `DynResidue`
- Added `DynResidue::one()`
=> Add windowed exponentiation for (Dyn)Residue

src/uint/modular/constant_mod.rs
These are defined in `modular::constant_mod::macros` module.
It was previously `pub`, but to shorten things up this commit makes that module private and re-exports the macros from `modular::const_mod`.
=> Re-export `constant_mod` macros from the parent module

src/uint/modular.rs, src/uint/modular/constant_mod.rs, src/uint/modular/constant_mod/const_sub.rs, src/uint/modular/runtime_mod.rs, src/uint/modular/runtime_mod/runtime_sub.rs, src/uint/modular/sub.rs
Not sure about adding `neg()`:
- Should there be a separate `NegResidue` trait, or should it be a part of `SubResidue`?
- The default implementation (via `SubResidue`) would require an access to zero, and therefore an additional trait bound, which `DynResidue` does not implement.
=> Add `SubResidue` trait and impls for `Residue` and `DynResidue`

src/uint/div_limb.rs
In `div2by1()`, there is a following part (simplified):
```
if r >= d {
q1 = q1 + 1
}
```
If we're inside it, `q1 < Word::MAX` and there is no overflow. But since we're doing it in constant-time, we have to calculate this new `q1` anyway, and therefore it may overflow. So I used a `wrapping_add()` there instead.
=> Fix integer overflow in `div2by1()`

src/limb/bits.rs, src/uint/bits.rs, src/uint/div_limb.rs
Is there some reason `bits_vartime()` returns `usize` and not `u32` like the corresponding methods of primitive types?
=> Add constant-time `leading_zeros()`, `trailing_zeros()`, `bits()`, and `bit()` for `Uint`

benches/bench.rs, src/limb.rs, src/limb/add.rs, src/limb/bits.rs, src/limb/cmp.rs, src/limb/encoding.rs, src/limb/mul.rs, src/limb/sub.rs, src/nlimbs.rs, src/traits.rs, src/uint.rs, src/uint/bits.rs, src/uint/cmp.rs, src/uint/div.rs, src/uint/encoding.rs, src/uint/from.rs, src/uint/modular.rs, src/uint/modular/constant_mod/const_add.rs, src/uint/modular/constant_mod/const_inv.rs, src/uint/modular/constant_mod/const_pow.rs, src/uint/modular/constant_mod/const_sub.rs, src/uint/modular/constant_mod/macros.rs, src/uint/modular/pow.rs, src/uint/rand.rs, src/uint/shl.rs, src/uint/shr.rs, tests/proptests.rs
Fixes #154
- rename `BIT_SIZE` to `BITS` and `BYTE_SIZE` to `BYTES` to match the constants in the primitive types
- add `BITS` and `BYTES` to `Uint` (instead of only having them in `Encoding`), similarly to how it's done for `Limb`
Now about the `usize` -> `u32`, I've tried to implement that, and I am reconsidering it. It really feels more natural in many places to have those constants be `usize`, otherwise there's a lot of `as` casts necessary (unless we also have `const LIMBS: u32`). `leading_zeros()` etc can be made to return `u32` more easily, but that would introduce an inconsistency with `BITS`. Perhaps we can leave the types as is after all.
=> Rename `BIT_SIZE` -> `BITS`, `BYTE_SIZE` -> `BYTES`

benches/bench.rs, src/limb.rs, src/limb/encoding.rs, src/traits.rs, src/uint.rs, src/uint/modular.rs, src/uint/modular/constant_mod.rs, src/uint/modular/constant_mod/const_add.rs, src/uint/modular/constant_mod/const_inv.rs, src/uint/modular/constant_mod/const_mul.rs, src/uint/modular/constant_mod/const_neg.rs, src/uint/modular/constant_mod/const_pow.rs, src/uint/modular/constant_mod/const_sub.rs, src/uint/modular/runtime_mod.rs, src/uint/modular/runtime_mod/runtime_add.rs, src/uint/modular/runtime_mod/runtime_inv.rs, src/uint/modular/runtime_mod/runtime_mul.rs, src/uint/modular/runtime_mod/runtime_neg.rs, src/uint/modular/runtime_mod/runtime_pow.rs, src/uint/modular/runtime_mod/runtime_sub.rs, tests/proptests.rs
- Remove `AddResidue`, `SubResidue`, `MulResidue`, `InvResidue`, `PowResidue`
- Impl `Add`, `Mul`, `Sub`, and `Neg` for `Residue` and `DynResidue` (also the combinations of by-ref and by-value, and the corresponding `const fn`s)
- Add `Pow`, `Invert` and `Square` traits, and impl them for `Residue` and `DynResidue`
- Add `PowBoundedExp` (hosting the former `pow_specific()` functionality) and a generic impl of `Pow` for `Bounded` exponents via this trait
- Remove `GenericResidue` trait
- Add `Retrieve` trait
- Add `Bounded` trait hosting `BITS` and `BYTES` constants which were formerly in `Encoding`
=> Use built-in traits for `(Dyn)Resiude`

src/traits.rs, src/uint.rs
Makes all of `Uint`'s inherent constants available through the `Integer` trait as well.
This is needed for the `elliptic-curve` crate, which uses the `Integer` trait and accesses some of these constants.
=> Add `BITS`, `BYTES`, and `LIMBS` to `Integer` trait

Cargo.toml, src/limb/rand.rs, src/non_zero.rs, src/traits.rs, src/uint/rand.rs
More succinct marker trait introduced in `rand_core` v0.6.4
=> Use `CryptoRngCore`

.github/workflows/crypto-bigint.yml, src/array.rs, src/checked.rs, src/lib.rs, src/limb.rs, src/limb/from.rs, src/limb/rand.rs, src/non_zero.rs, src/traits.rs, src/uint.rs, src/uint/array.rs, src/uint/encoding.rs, src/uint/encoding/der.rs, src/uint/encoding/rlp.rs, src/uint/from.rs, src/uint/rand.rs, src/wrapping.rs
Replace manual `cfg(doc(...))` annotations with automatic generation
=> Use `doc_auto_cfg`

src/uint/modular/constant_mod.rs, src/uint/modular/constant_mod/macros.rs
This makes it easier to handle `ResidueParams` and `Residue` in generic code.
=> Require some additional traits for `ResidueParams`

src/uint/div.rs, src/uint/modular.rs, src/uint/modular/constant_mod/macros.rs, src/uint/modular/reduction.rs, src/uint/modular/runtime_mod.rs, tests/impl_modulus.rs
Previously it was impossible to use `impl_modulus!` in crates that use crypto-bigint, because certain functions were only available within the crypto-bigint crate.
=> Make `impl_modulus!` usable from external crates

src/limb/mul.rs, src/uint/mul.rs
One of the "primes" in a list used in tests was accidentally 256 instead of 257.
This had no actual impact on the test and they continue to pass.
=> crypto-bigint: fix test vectors

src/uint.rs
These are useful for P-224 and P-521 respectively.
They're gated on the target using 32-bit limbs (since neither is a multiple of 64).
fiat-crypto provides P-224 field arithmetic for 32-bit platforms that uses 7 limbs, for example.
=> Define `U224` and `U544` on 32-bit platforms

src/uint/concat.rs
I believe that when the order of the result tuple in`UInt::mul_wide` was changed the conversion in `concat.rs` was missed out.
=> Fix convert from tuple

src/uint/modular/constant_mod/macros.rs, tests/const_residue.rs
(Since the old PR had bad formatting, I'm opening this instead)
=> Fix #191 by using a module path available from the outside of the create

src/limb.rs, src/uint.rs
Instead of deriving `Debug`, uses the `UpperHex` impls to print a hex inspection of the inner value.
=> Improve `Debug` impls on `Limb` and `Uint`

.github/workflows/crypto-bigint.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/crypto-bigint/actions/runs/4408297481:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …
=> Replace unmaintained actions-rs/* actions in CI workflows

src/uint/modular/runtime_mod.rs
The functionality I would like to have:
- extract `DynResidueParams` from a `DynResidue` object (to be able to, given one residue, initialize another one with the same params);
- extract the modulus from `DynResidueParams` (to be able to implement some modulus-depending algorithms, e.g. square root)
*Edit:* I decided to wait on exposing the Montgomery form for now; I will just retrieve before serializing. Exposing it exposes the specific representation used by the residue, and the API needs some thought, e.g. whether we do a range check when assembling a `DynResidue` from the pre-calculated Montgomery form and params.
Changes:
- Added `DynResidueParams::modulus()`
- Added `DynResidue::params()`
=> Expose residue params and modulus in `DynResidue`

benches/bench.rs, src/ct_choice.rs, src/uint/add_mod.rs, src/uint/modular/reduction.rs, src/uint/modular/runtime_mod.rs, src/uint/sub_mod.rs
- Added benchmarks for Montgomery multiplication and DynResidueParams creation
- Replaced the final reduction in `montgomery_reduction()` with `sub_mod_with_hi()`. Speeds it up by ~20% (for `U256`), I guess due to better vectorization?
- Extracted `muladdcarry()` from `montgomery_reduction()`
- Simplified `Uint::sub_mod()`, `sub_mod_special()`, `add_mod()`, `add_mod_special()` by reusing existing methods.
- Made `DynResidueParams::new()` a `const fn`
- Optimized `mod_neg_inv` calculation in `DynResidueParams::new()`, speeds it up by ~10% (for `U256`).
Originally I wanted to implement Montgomery multiplication by simultaneous multiplication + reduction instead of `mul_wide`, but it showed exactly the same performance, with the exception of the last reduction part - that's how I discovered …
=> Montgomery multiplication improvements

benches/bench.rs, src/ct_choice.rs, src/uint/modular/reduction.rs, src/uint/sub_mod.rs
Some minor internal things:
- simplify benchmarks by using `iter_batched()` (and regroup them more logically)
- make a debug assert in `CtChoice::from_lsb()` more consistent with the docstring
- move `sub_mod_with_hi()` to `Uint` near `sub_mod()`, since they're very similar
=> Housekeeping fixes

src/uint/modular.rs, src/uint/modular/constant_mod.rs, src/uint/modular/div_by_2.rs, src/uint/modular/runtime_mod.rs, tests/proptests.rs
For a given `x`, the method finds `y` such that `y + y = x mod p`. 
I understand the method may seem kind of niche. I need it for an efficient way of generating Lucas sequences (see https://doi.org/10.1090/mcom/3616, where Eqs. 16-17 require division by 2). But one can view it as a counterpart of modular square root, just for addition instead of multiplication. 
Technically this can be extended to regular Uints, but then it would have to return a CtOption (to cover the cases with odd `x` and even `p`).
=> Add `div_by_2()` method for integers in Montgomery form

src/uint/modular/div_by_2.rs, src/uint/shr.rs
A minor improvement I missed in the original PR.
- use `shr_1()` instead of calling `is_odd()` separately
- update the docstring of `shr_1()` to reflect that it now returns a `CtChoice`
=> Div-by-2 adjustment

Cargo.toml
If someone tries to use, e.g. `serde_json` as a serialization library with crypto-bigint `UInt`s, currently this fails at runtime:
```
Error("serializer is human readable, which requires the `alloc` crate feature", line: 0, column: 0)
```
This arises from the `serdect` dependency. There's currently no way to pass the `alloc` flag down through crypto-bigint.
The proposed solution here just piggybacks on the crypto-bigint `alloc` flag to also pass it down to `serdect`, but only if that dependency has been realized. Another option would be to always always enable `serdect/alloc` when `serde` is requested:
```toml
alloc = []
serde = ["serdect/alloc"]
```
or offer a new feature altogether to keep all the user's options open:
```toml
alloc = []
serde = ["dep:serdect"]
serde-alloc = ["serde", …
```
=> Fix serdect usage

src/uint/modular/constant_mod.rs, src/uint/modular/runtime_mod.rs
Fixes #236 
Also adds creation of a DynResidue from a Residue.
=> Expose montgomery form in Residue/DynResidue

src/ct_choice.rs, src/uint/cmp.rs
This optimizes Eq for Uint to avoid comparing the two values twice. `cmp_vartime` is added for cases where a short-circuiting comparison is sufficient.
=> Add cmp_vartime, faster Eq for Uint

src/uint/modular/runtime_mod.rs
Currently, `DynResidue` does not support zeroizing. This PR implements it, albeit probably controversially.
Adding zeroizing suppport seems tricky, in part because modulus parameters are [stored in the struct](https://github.com/RustCrypto/crypto-bigint/blob/85f0f6e7aaad608020538f41dbb57efab0f41615/src/uint/modular/runtime_mod.rs#L67). The question becomes what to do with them. Are they left alone? Are they set internally to all zeros? Are they set to some nominal but valid modulus?
The case for `Residue` is more clear, since its modulus parameters are generic.
This PR makes the design choice to leave the `DynResidue` parameters alone, which has two potential advantages:
- The treatment of modulus parameters is somewhat unified in both `Residue` and `DynResidue`
- The zeroized …
=> Add zeroizing to `DynResidue`

src/uint/modular/constant_mod/const_pow.rs, src/uint/modular/pow.rs, src/uint/modular/runtime_mod/runtime_pow.rs
This is a minimal change that allows working with exponents of a different size than the base for `Residue` and `DynResidue`.
Resolves #234 
Partially replaces the need for #230
=> Make pow work with different sized exponents

src/uint/add.rs, src/uint/rand.rs, src/uint/sqrt.rs, src/uint/sub.rs, tests/proptests.rs
Some small things that were picked up by the security audit.
- Removed conditionals in `Uint::saturating_add` and `saturating_sub` and replaced them with constant-time methods.
- Made checks in the `random_mod` test more logical
- Marked `Uint::sqrt` to be renamed to `sqrt_vartime` (and similarly `checked_sqrt` and `wrapping_sqrt`) on the next breaking release, since that's the crate's convention.
=> NCC audit fixes

src/uint/bits.rs
As far as I can tell it's not a breaking change.
=> Use references in bit-twiddling methods of `Uint`

src/non_zero.rs
This will allow us to make a number of methods `const fn` (for example, various division methods) and introduce `NonZero` bounds where they were previously impossible (for example, `inv_mod.rs` methods where moduli are currently just `&Self`). Also it opens up a possibility to initialize a `NonZero` constant of a modulus/divisor known at compile-time, so that it doesn't have to be unwrapped every time on use.
=> Add `const fn` constructors for `NonZero<Uint>` and `NonZero<Limb>`

benches/bench.rs, src/ct_choice.rs, src/limb/shl.rs, src/limb/shr.rs, src/uint.rs, src/uint/shl.rs, src/uint/shr.rs, tests/proptests.rs
This overrides the `shr()` implementation in #263 - this one is more efficient (O(LIMBS * log2(BITS)) instead of O(LIMBS^2)). For `U2048` it's ~10x slower than the vartime equivalent.
Question for @tarcieri : what behavior do we want on overflow? `shl()`/`shr()` currently return 0, their vartime equivalents return the original value. I wonder if it would be better to return a pair `(Self, CtChoice)` where the second element indicates the overflow.
=> Add constant-time `Uint::shr()` and `Uint::shl()`

.github/workflows/crypto-bigint.yml, src/boxed/uint/add.rs, src/checked.rs, src/limb.rs, src/non_zero.rs, src/uint.rs, src/uint/div.rs, src/uint/encoding/rlp.rs, src/uint/modular/constant_mod/const_inv.rs, src/wrapping.rs
Fix a bunch of clippy warnings that are raised with Rust 1.72, but do not appear in CI which uses 1.65 for clippy. Makes it easier to run clippy during development. Clippy bumped to 1.72 in CI.
I decided to go with `#![allow(clippy::unwrap_used)]` for test submodules instead of replacing each `unwrap()` there with `expect()`.
=> Fix clippy warnings

benches/bench.rs, src/ct_choice.rs, src/uint/bits.rs, src/uint/inv_mod.rs, src/uint/modular/constant_mod/macros.rs, src/uint/modular/runtime_mod.rs, tests/proptests.rs
- fix a typo in a proptest for `rem()` which rendered it useless
- make `inv_mod2k()` constant-time both in `self` and `k`
- rename the old `inv_mod2k()` to `inv_mod2k_vartime()`
- make the code in `inv_mod2k_vartime()` clearer and fix the attribution
- add a constant-time `inv_mod()` that supports both even and odd moduli (works via RNS and `inv_mod2k()`/`inv_odd_mod()`; another approach is binary GCD (see #227 for more info) which may or may not be faster, but is definitely more complicated)
Note that this PR does not introduce any backwards-incompatible changes (except for the performance regression for the users of `inv_mod2k()`).
Possible additions:
- We can add `inv_mod2k_bounded()`, for the cases where a bound on `k` is known. 
- We can add `inv_mod_vartime()` (that calls …
=> Modular inversion improvements

src/limb/bits.rs, src/uint/bits.rs
Adds `trailing_ones[_vartime]()`, `trailing_zeros_vartime()`, `leading_zeros_vartime()`
=> Add more bit-counting functions

src/uint/rand.rs
The current version of `Uint::random_mod()` produces different results on 32- and 64-bit targets because it exhausts the byte stream differently if the number of bytes in `modulus` is not a multiple of 8 (e.g. if it is 20 bytes, the 32-bit version will read 20 bytes - 5 limbs, but the 64-bit version will read 24 bytes - 3 limbs). This PR makes the behavior identical, so that an RNG with the same seed will produce the same stream of `Uint`s (as long as the RNG itself produces the bytestream consistently, of course). 
I am not sure if that is actually a desired behavior, but I did bump into it when I generated a ZK proof challenge on a 64-bit and 32-bit clients, and expected them to be the same. If it is not a guarantee we want to provide, perhaps an explicit note in the docs will be …
=> Make `Uint::random_mod()` work identically on 32- and 64-bit targets

src/uint/array.rs
This was needed in https://github.com/RustCrypto/elliptic-curves/pull/964, but only in testing.
Feel free to close if this isn't a good justification.
=> Implement `ArrayEncoding` for `U832`

src/checked.rs, src/uint/add_mod.rs, src/uint/div.rs, src/uint/div_limb.rs, src/uint/modular/constant_mod.rs, src/uint/modular/runtime_mod.rs, src/uint/mul_mod.rs, src/uint/neg_mod.rs, src/uint/sub_mod.rs
The front of the repo explicitly states under Goals:
"Constant-time by default. Variable-time functions are explicitly marked as such."
Some constant-time functions in the repo are documented that they run in constant-time, while other constant-time functions do not. This inconsistency may lead a newcomer to question if a function is constant-time despite being explicitly chosen as such. This simple PR updates the docs on the functions in question to avoid confusion and remain consistent with the stated goals of the repo.
=> Update docs for consistency

Cargo.lock, Cargo.toml
This version bump does not signify a release, but that we are starting a new round of breaking changes, as proposed in #268.
The first actual prerelease with an associated crate released to crates.io will be versioned v0.6.0-pre.0.
=> Bump version to v0.6.0-pre

src/traits.rs
This helps with deserialization - one doesn't need to create a mutable buffer and use a special purpose `deserialize` mutating its argument (like `serdect` does currently), but instead one can just use a standard `deserialize` with the API compatible with that of `#[serde(with)]` that returns the `Repr` object.
=> Add `TryFrom<&[u8]>` bound to `Encoding::Repr`

benches/bench.rs, src/uint/modular/runtime_mod.rs, src/uint/modular/runtime_mod/runtime_add.rs, src/uint/modular/runtime_mod/runtime_sub.rs, tests/proptests.rs
Renames the former `DynResidueParams::new_checked` to `::new`, eliminating the potential panic condition and returning `CtOption` instead.
=> Make `DynResidueParams::new` fallible

src/macros.rs
These macros are designed to allow assertions around const generics, however the previous implementation had a number of deficiencies, most notably it only worked if the constant name was `N`.
This changes the macro "type signature" to ensure the first parameter is an `ident`, but additionally it also contained baked-in assumptions that its type is `usize`. This change also explicitly documents that it only works on `usize` constants, although it'd be nice if it weren't so constrained.
=> `const_assert_eq`/`const_assert_ne` fixups

src/uint/modular.rs, src/uint/modular/constant_mod.rs, src/uint/modular/constant_mod/const_add.rs, src/uint/modular/constant_mod/const_inv.rs, src/uint/modular/constant_mod/const_mul.rs, src/uint/modular/constant_mod/const_neg.rs, src/uint/modular/constant_mod/const_pow.rs, src/uint/modular/constant_mod/const_sub.rs, src/uint/modular/runtime_mod.rs, src/uint/modular/runtime_mod/runtime_add.rs, src/uint/modular/runtime_mod/runtime_inv.rs, src/uint/modular/runtime_mod/runtime_mul.rs, src/uint/modular/runtime_mod/runtime_neg.rs, src/uint/modular/runtime_mod/runtime_pow.rs, src/uint/modular/runtime_mod/runtime_sub.rs
- Moves module-level comments to modules
- Gets rid of newlines between imports that get auto-sorted by rustfmt
=> crypto-bigint: formatting cleanups

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, README.md
Updates the following dependencies:
$ cargo update
Updating crates.io index
Adding aho-corasick v1.1.2
Updating anstyle v1.0.0 -> v1.0.4
Updating bitflags v2.4.0 -> v2.4.1
Updating bumpalo v3.12.0 -> v3.14.0
Updating bytes v1.4.0 -> v1.5.0
Removing cc v1.0.79
Updating ciborium v0.2.0 -> v0.2.1
Updating ciborium-io v0.2.0 -> v0.2.1
Updating ciborium-ll v0.2.0 -> v0.2.1
Updating clap v4.3.0 -> v4.4.8
Updating clap_builder v4.3.0 -> v4.4.8
Updating clap_lex v0.5.0 -> v0.6.0
Removing crossbeam-channel v0.5.7
Updating crossbeam-epoch v0.9.14 -> v0.9.15
Updating crossbeam-utils v0.8.15 -> v0.8.16
Updating either v1.8.1 -> v1.9.0
Removing errno v0.2.8
Removing errno v0.3.1
Adding errno v0.3.7
Removing errno-dragonfly v0.1.2
Updating fastrand v1.9.0 -> v2.0.1
Updating getrandom v0.2.8 -> v0.2.11 …
=> Cargo.lock: bump dependencies; MSRV 1.70

benches/bench.rs, src/uint.rs, src/uint/modular.rs, src/uint/modular/constant_mod.rs, src/uint/modular/constant_mod/macros.rs, tests/const_residue.rs, tests/proptests.rs
Removes the `constant_mod` and `runtime_mod` modules from the public API, re-exporting their types under `modular`.
In place of a module-level separation, this adds documentation with separate sections for constant versus runtime-dynamic moduli.
=> Flatten `uint::modular`

.github/workflows/crypto-bigint.yml, benches/bench.rs
Benchmarks weren't building without the `alloc` feature.
Also adds CI that ensures the benchmarks build with no features.
=> Fix benchmark build

src/boxed/uint.rs, src/boxed/uint/sub.rs
Implements basic subtraction support for `BoxedUint`.
=> Add `BoxedUint::{sbb, wrapping_sub, checked_sub}`

src/boxed/uint.rs
It was previously a `Vec<Limb>`, however this encourages changing the precision of an existing `BoxedUint` when they're supposed to be fixed-precision.
Using `Box<[Limb]>` decreases the on-stack size by eliminating the capacity and discourages changing the underlying precision, whereas `Vec` makes that convenient.
=> BoxedUint: change internal representation to `Box<[Limb]>`

src/boxed/uint.rs, src/boxed/uint/mul.rs, src/uint/mul.rs
Implements basic multiplication support for `BoxedUint`.
=> Add `BoxedUint::mul`

Cargo.toml, src/boxed/uint.rs, src/boxed/uint/encoding.rs, src/lib.rs, src/limb/encoding.rs, src/uint/encoding.rs
Initial support for decoding `BoxedUint` from a byte slice.
Decoding is fallible and paramaterized around an expected precision. Requiring a known precision at decode time allows the caller to ensure that all values are the same dynamically-determined size so as to prevent subsequent timing variability with respect to input sizes.
Decoding is currently constrained to inputs that are multiples of the word size.
=> Add `BoxedUint::{from_be_slice, from_le_slice}`

src/boxed/uint/encoding.rs
These functions allocate and return a boxed slice containing bytes serialized with the chosen endianness.
=> Add `BoxedUint::{to_be_bytes, to_le_bytes}`

src/traits.rs, src/uint/mul_mod.rs, tests/uint_proptests.rs
Uses Montgomery multiplication although it may not be the most efficient approach (e.g. a Barrett reduction might be faster).
This also changes the `MulMod` trait to remove the Montgomery-specific implementation details, allowing a simple `mul_mod(self, rhs, p)`. Optimized Montgomery multiplication is still available via `DynResidue`.
Closes #70
=> Impl `MulMod` for `Uint`

src/boxed/uint.rs, src/boxed/uint/cmp.rs, src/boxed/uint/sub.rs
Previously it swapped the arguments if one was shorter. This needs to be reflected in the argument ordering to the callback.
Unfortunately the existing tests didn't catch this, so they've been updated with a case that does.
=> BoxedUint: fix argument ordering to `::chain`

src/traits.rs
Bounds `Integer` types on:
- `AddMod`
- `SubMod`
- `NegMod`
- `MulMod`
=> Integer: add `*Mod` ops to bounds

src/boxed/uint.rs, src/boxed/uint/modular.rs, src/boxed/uint/sub_mod.rs, src/uint/modular.rs, src/uint/modular/reduction.rs
Adds an internal `impl_montgomery_reduction!` macro which can be used to abstract over `const fn` use cases as well as `BoxedUint` use cases which would require `const_mut_refs` to be usable from a `const fn`.
This is used to define an inner `mul_montgomery_from` function which works on `BoxedUint`.
It isn't yet tested/used and marked as `allow(dead_code)`, but I'd like to perform some major refactoring without losing these changes.
=> Montgomery multiplication support for `BoxedUint`

src/uint/boxed.rs, src/uint/boxed/add.rs, src/uint/boxed/bit_and.rs, src/uint/boxed/cmp.rs, src/uint/boxed/sub.rs, tests/boxed_uint_proptests.rs
The two APIs are nearly identical. The only difference is the latter is infallible and panics if an invalid precision is given.
This also changes `BoxedUint::max` to have the same behavior.
Whether they should panic is a debatable point. Indeed having both options would be good, but it should probably return `CtOption` where `BoxedUint::max` was returning `Option`.
Regardless, this removes duplication and makes the API at least more consistent with itself.
=> Replace `BoxedUint::new` with `::zero_with_precision`

src/uint/boxed.rs, src/uint/boxed/bits.rs, tests/boxed_uint_proptests.rs
Adds a function for counting the number of bits in a value, i.e. the index of the highest set bit.
Since `BoxedUint` isn't `const fn`, this can be implemented in constant-time using `subtle`.
=> Add `BoxedUint::bits`

src/uint/boxed.rs
This is an inherent function with the same type signature as `subtle::ConditionallySelectable::conditional_select`, however we can't impl the upstream trait because it has a `Copy` bound.
See dalek-cryptography/subtle#94.
=> Add `BoxedUint::conditional_select`

src/limb/bit_or.rs, src/uint/boxed.rs, src/uint/boxed/bit_or.rs, src/uint/boxed/bits.rs, src/uint/boxed/inv_mod.rs
Support for computing inverses modulo powers of 2.
The `bitor` impl was needed to test `inv_mod2k`, which internally uses a `set_bit` function that needed tested.
=> Add `BoxedUint::{inv_mod2k, bitor}`

src/modular/boxed_residue.rs, src/modular/boxed_residue/mul.rs, src/modular/boxed_residue/pow.rs, tests/boxed_residue_proptests.rs
Initial support for modular exponentiation, adapted from the original implementation of `pow_montgomery_form` this crate used prior to #248:
https://github.com/RustCrypto/crypto-bigint/blob/4838fd96e1bde8b0c5e0ce691c366c7ec930e466/src/uint/modular/pow.rs
Proptested against `num_bigint::BitUint::modpow`.
=> Add `BoxedUint::pow`

Cargo.lock, Cargo.toml, src/uint/boxed.rs, src/uint/boxed/add.rs, src/uint/boxed/bits.rs, src/uint/boxed/encoding.rs, src/uint/boxed/inv_mod.rs, src/uint/boxed/mul.rs, src/uint/boxed/neg.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs, src/uint/boxed/sub.rs, tests/boxed_uint_proptests.rs, tests/uint_proptests.rs
Support for computing modular inverses, proptested against the implementation in `num-bigint-dig`, which this commit also switches to (`num-bigint` doesn't provide an implementation we can test against).
Uses the same method as `Uint::inv_mod`, namely an algorithm equivalent to GMP's `mpn_sec_invert`, with code largely duplicated from the `Uint` version.
Notably this version is variable time with respect to the modulus, which might be avoidable with alternative implementations, such as Bernstein-Yang.
It would also be nice to deduplicate the implementation, though reuse between `const fn` use cases and heap-backed use cases is difficult.
This additionally adds the following prerequisites:
- `BoxedUint::{conditional_assign, conditional_swap, is_one}
- `BoxedUint::conditional_wrapping_*` …
=> Add `BoxedUint::inv_mod`

src/modular/boxed_residue.rs, src/modular/boxed_residue/inv.rs, src/uint/boxed/inv_mod.rs, tests/boxed_residue_proptests.rs
=> Impl `Invert` for `BoxedResidue`

src/modular/boxed_residue.rs, src/uint/boxed.rs, src/uint/boxed/mul_mod.rs, tests/boxed_residue_proptests.rs, tests/boxed_uint_proptests.rs
Like the `MulMod` impl on `Uint`, a more efficient implementation is possible (as noted in the comments), but for now this gets the job done.
=> Impl `MulMod` for `BoxedUint`

src/modular/boxed_residue/mul.rs, src/uint/boxed.rs, src/uint/boxed/add_mod.rs, src/uint/boxed/div.rs, src/uint/boxed/sub_mod.rs
Several functions on the `Boxed*` types don't yet support implicit widening (#312) and will panic if two or more operands are not the same size (NOTE: we should eventually fix this)
Some of these functions previously had debug asserts that the number of limbs are equal, however that's less helpful information when trying to debug these problems than the precision in bits.
This changes all of the assertions for size equality to use `bits_precision`.
=> Assert `Boxed*` size equivalance using `bits_precision`

src/uint/boxed.rs, src/uint/boxed/rand.rs, src/uint/rand.rs
Impls the `RandomMod` trait for `BoxedUint`, sharing an implementation with `Uint`.
The `Random` trait can't be impl'd since we need to specify a precision as an argument. Perhaps we need a trait like `RandomWithPrecision`.
=> `BoxedUint` random number generation

src/uint/boxed.rs
Uses a derived impl. Ideally this wouldn't be used with secret values, or at least hopefully with a good hashing algorithm (like the default SipHasher, which is a secure PRF)
=> Impl `Hash` for `BoxedUint`

src/uint/boxed.rs, src/uint/boxed/ct.rs
Unfortunately `BoxedUint` can't impl `subtle::ConditionallySelectable` due to a supertrait bound on `Copy`. See dalek-cryptography/subtle#94
This bound is required by `CtOption::map` and `CtOption::and_then` which are important for writing constant-time code.
As a workaround which makes it still possible to leverate `CtOption`, this adds special `BoxedUint`-specialized combinators that are able to work around this issue by generating a placeholder (zero) value to pass to the provided callbacks in the event `CtOption` is none.
This requires branching on the output of `CtOption` (which is unavoidable without an upstream fix in `subtle` itself), but still ensures that the provided callback function is called with a `BoxedUint` of a matching number of limbs regardless of whether the …
=> BoxedUint: add `cond_map` and `cond_and_then`

src/uint/boxed.rs, src/uint/boxed/add.rs, src/uint/boxed/bit_and.rs, src/uint/boxed/bit_or.rs, src/uint/boxed/sub.rs
Splits apart the internal functions for iterating over limbs and handling widening, and applying a given function to the inputs.
`BoxedUint::map_limbs` is useful when there is no carry.
The somewhat ambiguously named `BoxedUint::chain` has also been renamed to `BoxedUint::fold_limbs` which better reflects the combinator being applied.
=> BoxedUint: add `map_limbs`; rename `fold_limbs`

src/modular/boxed_residue.rs, src/modular/boxed_residue/inv.rs, src/modular/boxed_residue/mul.rs, src/uint/boxed/mul.rs, src/uint/boxed/mul_mod.rs, tests/boxed_uint_proptests.rs
This is more consistent with `Uint`, where `mul` returns an output whose limbs are equal to the sum of the input limb counts.
`Uint::mul_wide` returns a tuple of lo and hi components, with `Uint::mul` handling the concatenation.
=> BoxedUint: rename `mul_wide` to `mul`

src/uint/boxed/mul.rs, src/uint/mul.rs
Uses a common implementation of schoolbook multiplication factored into the `uint::mul` module.
For now, it's impl'd as a macro to share a common implementation between `const fn` and heap-backed `BoxedUint`, since `const_mut_refs` is not yet stable and needed to be able to write into a non-array output.
=> BoxedUint: share `Mul` impl with `Uint`

src/traits.rs, src/uint.rs
Adds a trait specifically for `Uint`-like fixed-width integers whose size is known at compile time.
Also adds a blanket impl of the `Integer` trait for all `FixedInteger` types, and adds a default impl of `is_odd` to `Integer`.
=> Add `FixedInteger` trait

src/traits.rs
Allows `Integer` to be impl'd for non-`Copy` types.
The bound on `Integer` is replaced by `Clone` to cover the same use cases.
=> Move `Copy` bound from `Integer` => `FixedInteger`

src/traits.rs, src/uint.rs, src/uint/bits.rs, src/uint/boxed.rs, src/uint/boxed/bits.rs, tests/boxed_uint_proptests.rs, tests/uint_proptests.rs
Adds the following methods:
- `bits`: count the number of bits required to represent a given number in constant-time
- `bits_vartime`: count the number of bits required to represent a given number in variable-time
- `leading_zeros`: count the number of leading zeros in a number, implemented as a provided method which subtracts `bits` from `bits_precision`.
This also adds `BoxedUint::bits_vartime`, whereas previously it only had a constant-time implementation.
=> Integer: add `bits(_vartime)` and `leading_zeros` methods

src/traits.rs
Adds bounds for the following to `Integer`:
- `BitAndAssign`
- `BitOrAssign`
- `BitXorAssign`
- `DivAssign`
- `ShlAssign`
- `ShrAssign`
Also adds bounds for:
- `From<u8>`
- `From<u16>`
- `From<u32>`
=> Integer: expand `*Assign` and `From` bounds

Cargo.toml, src/lib.rs, src/modular/boxed_residue.rs, src/modular/boxed_residue/neg.rs, src/uint/boxed/encoding.rs
- Impl `std::error::Error` for `DecodeError`
- Use `Arc` for storing `BoxedResidueParams` when available
=> Add `std` feature

src/limb/encoding.rs, src/macros.rs, src/uint/boxed.rs, src/uint/boxed/encoding.rs, src/uint/boxed/rand.rs, src/uint/rand.rs
I understand that this change may be controversial, but let me just put it out there. The reason being, why panic when we don't have to, and also to prevent bugs when something works on a 32 bit but doesn't on a 64 bit target.
- `BoxedUint::zero_with_precision()`, `one_with_precision()`, `max()` round up `bits_precision` to a multiple of `Limb::BITS`. It's a little weird in the case of `max()`, but I am not sure this method should be public in the first place (and perhaps should be renamed). 
- Support arbitrary `bits_precision` in `BoxedUint::random()` (generating a random number in range `[0, 2^bits_precision)`). 
- Fix the tests in `boxed/rand.rs` which didn't actually test `BoxedUint`. 
- Round up `bits_precision` when decoding `BoxedUint` from bytes, to match the constructors' …
=> Round up `bits_precision` when creating `BoxedUint`

src/modular.rs, src/modular/bernstein_yang.rs, tests/bernstein_yang_proptests.rs
Adapted from: https://github.com/privacy-scaling-explorations/halo2curves/pull/83
Original code is Apache 2.0+MIT. Attribution has been added to the top of the module.
See also: #227
cc @dignifiedquire @fjarri @mratsim
=> Bernstein-Yang modular inversion algorithm

src/uint/boxed/mul.rs, src/uint/mul.rs, tests/boxed_uint_proptests.rs
Uses a more efficient squaring algorithm with fewer iterations, with an implementation shared with `Uint`.
Proptested against `num-bigint`.
=> BoxedUint: improve efficiency of `square`

Cargo.toml, benches/dyn_residue.rs, benches/uint.rs
Splits apart the `Uint` and `DynResidue` benchmarks, in preparation for adding benchmarks for `BoxedUint` and `BoxedResidue`.
=> Reorganize benchmarks

src/uint/boxed/mul.rs, src/uint/mul.rs, tests/boxed_uint_proptests.rs
This reverts commit cd9cdcecf9cd27fae48843905581b053c31952e0.
Benchmarks reveal this caused a performance regression to modpow. Reverting it yields the following improvement:
```
time:   [76.362 µs 76.381 µs 76.403 µs]
change: [-72.846% -72.795% -72.747%] (p = 0.00 < 0.05)
```
=> Revert "BoxedUint: improve efficiency of `square` (#382)"

src/lib.rs, src/limb.rs, src/modular/div_by_2.rs, src/uint/boxed/shr.rs, src/uint/div.rs, src/uint/inv_mod.rs, src/uint/shl.rs, src/uint/shr.rs, src/uint/sqrt.rs
- Add `shl1` and `shr1` methods
- Change function for returning overflow bit to `shr1_with_overflow`
- Move `HI_BIT` to an inherent constant of `Limb`
=> Uint: bit shift improvements

src/uint/boxed/div.rs, src/uint/boxed/inv_mod.rs, src/uint/boxed/shr.rs
Analogous changes to #388 for `BoxedUint`, which eliminates some allocations by using in-place operations instead.
=> `BoxedUint`: bit shift improvements

benches/boxed_residue.rs, src/modular/boxed_residue.rs, src/modular/boxed_residue/add.rs, src/modular/boxed_residue/inv.rs, src/modular/boxed_residue/sub.rs, src/modular/reduction.rs, src/uint/boxed.rs, src/uint/boxed/add.rs, src/uint/boxed/mul_mod.rs, src/uint/boxed/sub.rs, src/uint/boxed/sub_mod.rs, tests/boxed_residue_proptests.rs
Eliminates several allocations by performing most operations of a Montgomery reduction in-place.
Only conditionally adding the modulus presently incurs an allocation.
```
Montgomery arithmetic/BoxedResidue creation
time:   [135.30 ns 135.50 ns 135.76 ns]
change: [-36.403% -36.104% -35.794%] (p = 0.00 < 0.05)
Montgomery arithmetic/BoxedResidue retrieve
time:   [203.59 ns 204.01 ns 204.45 ns]
change: [-17.533% -16.947% -16.403%] (p = 0.00 < 0.05)
Montgomery arithmetic/multiplication, BoxedUint*BoxedUint
time:   [223.19 ns 223.76 ns 224.40 ns]
change: [-19.576% -19.107% -18.645%] (p = 0.00 < 0.05)
time:   [58.927 µs 59.009 µs 59.103 µs]
change: [-18.486% -18.227% …
```
=> BoxedResidue: (almost) in-place Montgomery reductions

src/modular/reduction.rs, src/uint/boxed/add.rs, src/uint/boxed/inv_mod.rs, src/uint/boxed/sub.rs
Adds internal `conditional_adc_assign` and `conditional_sbb_assign` methods on `BoxedUint` which conditionally perform in-place addition/subtraction with carry.
This eliminates the last allocations in Montgomery reduction as well as a number of them in modular inversions.
```
Montgomery arithmetic/BoxedResidueParams creation
time:   [17.432 µs 17.453 µs 17.475 µs]
change: [-5.8279% -5.5913% -5.3509%] (p = 0.00 < 0.05)
Montgomery arithmetic/BoxedResidue creation
time:   [113.13 ns 113.75 ns 114.46 ns]
change: [-16.909% -16.489% -16.042%] (p = 0.00 < 0.05)
Montgomery arithmetic/BoxedResidue retrieve
time:   [167.52 ns 168.03 ns 168.56 ns]
change: [-18.571% -17.870% -17.225%] (p = 0.00 < 0.05)
Montgomery …
```
=> BoxedUint: implement in-place conditional addition/subtraction

src/modular/boxed_residue/mul.rs, src/modular/boxed_residue/pow.rs
Avoids allocating the immediate intermediate Montgomery form value used for modpow, instead performing multiply and squarings (partially) in-place.
```
time:   [44.597 µs 44.653 µs 44.706 µs]
change: [-13.255% -13.003% -12.759%] (p = 0.00 < 0.05)
```
=> BoxedResidue: use in-place Montgomery ops for modpow

src/modular/boxed_residue/pow.rs, src/uint/boxed.rs
Changes `BoxedUint::conditional_assign` to actually be an in-place operation rather than allocating, and uses it to impl `BoxedResidue::pow`.
This leads to a fairly significant performance increase.
```
time:   [27.769 µs 27.798 µs 27.830 µs]
change: [-39.063% -38.898% -38.724%] (p = 0.00 < 0.05)
```
=> BoxedResidue: use conditional assignment in `pow`

src/modular/boxed_residue/mul.rs, src/modular/boxed_residue/pow.rs, src/uint.rs, src/uint/boxed.rs, tests/boxed_residue_proptests.proptest-regressions
Performs Montgomery multiplications and squarings in-place, avoiding allocations, by constructing a reusable `MontgomeryMultiplier`.
```
time:   [24.265 µs 24.274 µs 24.288 µs]
change: [-24.321% -24.194% -24.081%] (p = 0.00 < 0.05)
```
=> BoxedResidue: avoid allocations in `pow` loop

src/uint/boxed.rs, src/uint/boxed/ct.rs
Groups all the `subtle`-based constant time code together under `uint::boxed::ct`.
This is mostly the `ConditionallySelectable`-alike methods, but we can't actually impl that trait due to its `Copy` bound.
=> BoxedUint: move `subtle` support into `ct` module

benches/boxed_residue.rs, benches/dyn_residue.rs, benches/uint.rs
This avoids the compiler potentially optimizing away part or all of an operation inside of a benchmark.
Using a larger `BoxedResidue` is both more indicative of real-world usages as well as reduces noise in the benchmark.
=> Use `black_box` on benchmarks; 4096-bit BoxedResidue

benches/boxed_residue.rs, src/modular/boxed_residue/mul.rs, src/modular/boxed_residue/pow.rs, src/modular/reduction.rs
Implements `BoxedResidue::pow` using the "almost Montgomery multiplication" method used by `num-bigint` as originally added in rust-num/num-bigint@f523b9c359b0b4e8718176aba693c6e061cd0353
=> `BoxedResidue::pow` using "almost Montgomery multiplication"

benches/boxed_residue.rs, src/modular/boxed_residue.rs, tests/boxed_residue_proptests.rs
Adds a variable-time constructor usable when the modulus is non-secret, such as is the case with RSA, providing a ~6X performance improvement.
```
Montgomery arithmetic/BoxedResidueParams::new
time:   [8.3193 ms 8.3255 ms 8.3326 ms]
```
```
Montgomery arithmetic/BoxedResidueParams::new_vartime
time:   [1.3982 ms 1.4002 ms 1.4022 ms]
```
=> Add `BoxedResidueParams::new_vartime`

src/non_zero.rs
When attempting to port over `dsa` to `crypto-bigint`, I noticed that the `NonZero` wrapper has no implementation for the `Zeroize` trait.  
That made it a bit annoying to implement the internals that expect the private factor `x` to be wrapped into a `Zeroizing` wrapper.
=> Implement `Zeroize` for `NonZero` wrapper

src/modular/boxed_residue.rs
When the `std` feature is available, allows passing `BoxedResidueParams` as an `Arc` which avoids unnecessary cloning.
=> Add `BoxedResidue::new_with_arc`

src/modular/boxed_residue.rs, src/modular/boxed_residue/pow.rs
Move asserts around to cover more cases and ensure that the output is fully reduced.
=> BoxedResidue: refactor asserts

src/modular/boxed_residue/mul.rs
This was previously written using raw `Word`s to ensure maximum performance, however it precludes access to the constant-time helper functions implemented on `Limb`.
This carefully rewrites the implementation to using `Limb` instead of `Word` while avoiding any performance impacts.
```
time:   [24.424 ms 24.444 ms 24.465 ms]
change: [-0.1629% -0.0399% +0.0760%] (p = 0.52 > 0.05)
No change in performance detected.
```
=> BoxedUint: use `Limb`s in `montgomery_mul`

Cargo.toml, benches/limb.rs
Adds benchmarks for constant-time comparison operations, with the goal of optimizing them better.
=> Limb: add initial benchmarks

src/limb/cmp.rs
Optimizes `ConstantTimeGreater`/`ConstantTimeLess` impls by using borrowing subtraction and checking whether a borrow occurred.
```
ops/ct_lt               time:   [900.95 ps 909.83 ps 922.37 ps]
change: [-76.095% -75.752% -75.373%] (p = 0.00 < 0.05)
```
```
ops/ct_gt               time:   [902.46 ps 938.83 ps 1.0134 ns]
change: [-55.763% -53.637% -50.192%] (p = 0.00 < 0.05)
```
=> Limb: optimize constant-time comparisons

src/ct_choice.rs, src/modular/boxed_residue.rs, src/modular/dyn_residue.rs, src/modular/residue/macros.rs, src/uint/boxed/inv_mod.rs, src/uint/inv_mod.rs, tests/uint_proptests.rs
- `inv_mod2k(_vartime)` return a tuple with the second parameter indicating whether the inverse exists
- In `inv_mod2k(_vartime)` docstrings, removed the note about `self` having to be less than `2^k` - the algorithm works just fine even if it's not
- Simplified the usage of `inv_mod2k` in the creation of `DynResidueParams`
- `inv_odd_mod()` now also returns a falsy `CtChoice` in case of an even modulus
=> Make `inv_mod2k(_vartime)` return a `CtChoice`

Cargo.toml, benches/boxed_uint.rs, benches/uint.rs, src/lib.rs, src/limb/bit_not.rs, src/limb/bit_or.rs, src/limb/bit_xor.rs, src/limb/bits.rs, src/limb/mul.rs, src/limb/shl.rs, src/limb/shr.rs, src/modular/div_by_2.rs, src/uint/boxed.rs, src/uint/boxed/bits.rs, src/uint/boxed/div.rs, src/uint/boxed/inv_mod.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs, src/uint/div.rs, src/uint/inv_mod.rs, src/uint/mul.rs, src/uint/shl.rs, src/uint/shr.rs, src/uint/sqrt.rs, tests/boxed_uint_proptests.rs, tests/uint_proptests.rs
A part of #268 
Fixes #121
- `const fn` bit shifts for `Uint` return the overflow status as `CtChoice` (and set the result to zero in that case, which is documented, so it's a part of the API now). `Option` would be better for the vartime shifts, but its methods are not `const` yet in stable.
- `shl/shr` for `BoxedUint` return `(Self, Choice)` (not `CtOption` since most of its methods need the type to be `ConditionallySelectable`, which `BoxedUint` isn't). The vartime equivalents return `Option<Self>`.
- operator impls panic on overflow (which is the default behavior for built-in integers)
- made the implementations in `uint/shl.rs` and `shr.rs` more uniform and improved vartime shift performance (before it was calling a constant-time shift-by-no-more-than-limb which added some overhead) …
=> Bring the overflow behavior in bit shifts in sync with `std`

benches/uint.rs, src/modular/dyn_residue.rs, src/modular/residue.rs, src/modular/residue/add.rs, src/modular/residue/inv.rs, src/modular/residue/macros.rs, src/modular/residue/mul.rs, src/modular/residue/pow.rs, src/modular/residue/sub.rs, src/non_zero.rs, src/uint/div.rs, src/uint/div_limb.rs, src/uint/mul_mod.rs, src/uint/sqrt.rs, tests/uint_proptests.rs
This simplifies the API allowing us to avoid returning `CtChoice` results, and making some methods redundant. Also that's what `BoxedUint` is already doing.
- Simplify `Reciprocal` API by taking a `NonZero<Limb>` in `Reciprocal::new()` which is now `const`.
- `Reciprocal::ct_new()` is removed. 
- `Uint::div_rem_limb()` and `Uint::div_rem_limb_with_reciprocal()` take a `NonZero<Limb>` and are now `const`.
- `Uint::ct_div_rem_limb()` and `Uint::ct_div_rem_limb_with_reciprocal()` are removed.
- `Uint::div_rem()` and `Uint::div_rem_vartime()` are now `const`.
- `Uint::const_div_rem()` and `Uint::const_div_rem_vartime()` are removed.
- Make `Uint::rem()` and `rem_wide()` take `NonZero` rhs and make them const.
- Make `Uint::wrapping_div(_vartime)` take `NonZero` rhs
- Wrap …
=> Make division methods take `NonZero`-wrapped divisors

src/ct_choice.rs, src/lib.rs, src/limb/cmp.rs, src/modular/div_by_2.rs, src/modular/dyn_residue/inv.rs, src/modular/inv.rs, src/modular/pow.rs, src/modular/residue.rs, src/modular/residue/inv.rs, src/non_zero.rs, src/uint/add.rs, src/uint/bits.rs, src/uint/boxed/cmp.rs, src/uint/boxed/inv_mod.rs, src/uint/cmp.rs, src/uint/div.rs, src/uint/div_limb.rs, src/uint/inv_mod.rs, src/uint/mul.rs, src/uint/neg.rs, src/uint/neg_mod.rs, src/uint/shl.rs, src/uint/shr.rs, src/uint/sqrt.rs, src/uint/sub.rs, tests/uint_proptests.rs
- Don't use "ct_" prefixes for constant-time methods - it is the default
- Renamed `CtChoice` to `ConstChoice` (to distinguish it from `subtle::Choice`)
=> Normalize the usage of prefixes for method names

src/modular/boxed_residue.rs, src/uint/boxed.rs, src/uint/boxed/inv_mod.rs, tests/boxed_residue_proptests.rs, tests/boxed_uint_proptests.rs
Avoid redefining these methods by using the provided impls on the trait
=> `BoxedUint`: use `Integer::{is_even, is_odd}`

src/traits.rs, src/uint/boxed.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs
Adds a method to the `Zero` trait for setting its value to zero in-place, subsuming the previous `BoxedUint::set_to_zero` function.
It's inspired by a similar method on `num_traits::Zero` (which we don't use so `is_zero` can return `Choice` and use `ConstantTimeEq` to compare values in constant-time).
https://docs.rs/num-traits/latest/num_traits/identities/trait.Zero.html#method.set_zero
=> Add `Zero::set_zero` method

src/uint/boxed/add.rs, src/uint/boxed/sub.rs
Uses `adc_assign`/`sbb_assign` to perform these operations in-place.
=> BoxedUint: optimized `AddAssign`/`SubAssign` impls

src/uint/boxed/shl.rs
Allows `shl_assign` to operate in-place on `self` (although it still requires a temporary buffer)
=> BoxedUint: optimize `shl_assign`

src/uint/boxed/shl.rs, src/uint/boxed/shr.rs
Allows `shl_assign` to operate in-place on `self` (although it still requires a temporary buffer), ala what #423 did for `shl_assign`
=> BoxedUint: optimize `shr_assign`

benches/boxed_uint.rs, benches/uint.rs, src/lib.rs, src/modular/div_by_2.rs, src/uint/boxed/div.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs, src/uint/div.rs, src/uint/inv_mod.rs, src/uint/mul.rs, src/uint/shl.rs, src/uint/shr.rs, src/uint/sqrt.rs, tests/boxed_uint_proptests.rs, tests/uint_proptests.rs
Changes all shift functions which return an overflow flag (as a `Choice` or `ConstChoice`) to use the `overflowing_sh*` name prefix, which aligns with similar APIs in `core`/`std`.
In their place, adds new `Uint::{shl, shr}` functions which provide the trait-like behavior (i.e. panic on overflow) but work in `const fn` contexts (and can now panic at compile time on overflow).
=> Align with `core`/`std` on `overflowing_sh*`

Cargo.toml, src/modular.rs, src/modular/dyn_residue.rs, src/modular/inv.rs, src/modular/mul.rs, src/modular/residue.rs, src/traits.rs, src/uint/add.rs, src/uint/boxed/add.rs, src/uint/boxed/mul.rs, src/uint/boxed/mul_mod.rs, src/uint/boxed/neg.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs, src/uint/boxed/sub.rs, src/uint/concat.rs, src/uint/div.rs, src/uint/mul.rs, src/uint/mul_mod.rs, src/uint/neg.rs, src/uint/shl.rs, src/uint/shr.rs, src/uint/sub.rs, tests/uint_proptests.rs
Until now we have used traits defined in this crate, primarily because many of these traits are predicates that return `bool` and in constant-time code we want those to return `Choice`/`CtOption`.
`Wrapping*` is an example of the sort of trait we'd want to incorporate unchanged, and there are potentially others, so this adds `num-traits` as a hard dependency (previously our only hard dependency was `subtle`). Note that `num-traits` itself has no transitive dependencies (or rather, they're optional but not enabled).
The `Wrapping*` traits have bounds on the corresponding op traits being impl'd with `Self` operands e.g. `WrappingAdd: Add<Self, Output = Self>` so this PR also adds impls of those traits.
We've previously avoided these as in `std` they panic on overflow/underflow in debug …
=> Impl `Wrapping*` traits from `num-traits`

src/uint/mul.rs
I'm not even sure what "HLIMBS" was supposed to stand for... high limbs perhaps?
It's a constant for the number of limbs in the `rhs` parameter, i.e. the right-hand operand, so this renames it to `RHS_LIMBS`, which is much easier to visually scan versus `LIMBS` than `HLIMBS` was.
=> Uint: rename `HLIMBS` to `RHS_LIMBS`

src/limb.rs, src/limb/add.rs, src/limb/mul.rs, src/limb/neg.rs, src/limb/shl.rs, src/limb/shr.rs, src/limb/sub.rs, src/uint.rs, src/uint/add.rs, src/uint/boxed.rs, src/uint/boxed/add.rs, src/uint/boxed/mul.rs, src/uint/boxed/neg.rs, src/uint/mul.rs, src/uint/neg.rs, src/uint/sub.rs, src/wrapping.rs
Impls `num_traits::{Zero, One}` for:
- `Limb`
- `Uint`
- `BoxedUint`
- `Wrapping`
To impl the traits for `Wrapping`, it required generic impls of `Add` and `Mul`, which are possible thanks to the `WrappingAdd`/`WrappingMul` traits.
These subsume the per-type impls that existed previously.
=> Expand `num_traits` impls

src/checked.rs, src/limb/add.rs, src/limb/mul.rs, src/limb/sub.rs, src/traits.rs, src/uint/add.rs, src/uint/boxed/add.rs, src/uint/boxed/div.rs, src/uint/boxed/mul.rs, src/uint/boxed/sub.rs, src/uint/div.rs, src/uint/mul.rs, src/uint/sub.rs
This crate defines its own `Checked*` traits in order to use `CtOption<T>` rather than `Option<T>`, however it gets its `Wrapping*` traits from `num-bigint`.
This brings the `Checked*` traits more in line with `Wrapping*`, automatically taking a reference to the `rhs` parameter, which eliminates the need to use HRTBs in `Integer`'s definition.
=> Bring `Checked*` traits in line with `Wrapping*`

src/traits.rs
Adds a number of new traits to the bounds including `Add`, `Sub`, and `Mul`, and expands HRTB coverage so that every trait which doesn't implicitly use `&Rhs` is covered for both owned and reference forms.
=> Expand `Integer` trait

.github/workflows/crypto-bigint.yml, Cargo.toml, README.md, src/modular/bernstein_yang.rs, tests/bernstein_yang_proptests.proptest-regressions, tests/bernstein_yang_proptests.rs
Refactors the `CInt` type into `Uint62L` which always uses a 62-bit unsaturated representation. This is mostly to reduce the overall number of const generic parameters involved, since Bernstein-Yang always uses a 62-bit unsaturated representation (at least as currently implemented).
Moves the `S` parameter from `invert` into the `BernsteinYangInverter` struct itself. This allows the type to always "know" its associated inverter, rather than leaving it up to the end user to calculate.
Also changes the `invert` method to accept a `Uint` as input.
=> Bernstein-Yang cleanups

src/modular/bernstein_yang.rs, src/traits.rs, src/uint.rs, src/uint/macros.rs, tests/bernstein_yang_proptests.rs
Adds a trait for obtaining a `BernsteinYangInverter` for the given `Uint` modulus, precomputing the number of unsaturated limbs needed for the 62-bit unsaturated form used by Bernstein-Yang at compile time, and associating the proper `BernsteinYangInverter` for a given `Uint` size as an associated type.
This should make it possible to obtain a `BernsteinYangInverter` for a `Residue`/`DynResidue`, though that's left as a followup exercise.
=> Add `Inverter` trait

src/macros.rs, src/modular/bernstein_yang.rs, src/traits.rs, src/uint.rs, src/uint/macros.rs, tests/bernstein_yang_proptests.rs
Adds a trait for abstracting over various sized `BernsteinYangInverter` (and prospectively a `BoxedBernsteinYangInverter`) types, which also opens the door to impl'ing `PrecomputeInverter` for `*ResidueParams`, where the inverter would accept a `*Residue` as input/output and invert in Montgomery form.
The `PrecomputeInverter::Inverter` type is now bounded on the new `Inverter` trait, making it useful in generic code.
=> Add new `Inverter` trait; rename `PrecomputeInverter`

src/modular/bernstein_yang.rs, src/traits.rs, src/uint/macros.rs, tests/bernstein_yang_proptests.rs
Adds a `ConstChoice` to the `const fn` versions of a Bernstein-Yang constructor as well as computing inversions on non-`NonZero` inputs.
Changes the `Inverter` trait to return `CtChoice` on non-`NonZero` inputs (`NonZero` inputs are still infallible).
The `PrecomputeInverter` impl on `Uint` now panics if called on an even modulus, which may not be ideal, but allows a prospective impl on `*ResidueParams` to be infallible, which is the main way this is intended to be used (though the impl on `Uint` will be the core).
=> Bernstein-Yang: fallible constructors; return `CtOption`

src/modular.rs, src/modular/bernstein_yang.rs, src/modular/residue.rs, src/modular/residue/inv.rs, tests/boxed_residue_proptests.rs
Adds support for computing modular inverses of `Residue`s using Bernstein-Yang.
The implementation supports fully `const fn` usage(!), as well as a trait-based API using the `Inverter` trait.
It's composed in terms of the `Inverter` impl on `Uint`.
Includes one test using the same vector as `Residue::invert`.
=> Add `ResidueInverter`

src/modular.rs, src/modular/dyn_residue.rs, src/modular/dyn_residue/inv.rs, src/modular/residue/inv.rs, src/traits.rs
Ala `ResidueInverter` added in #446, adds support for computing modular inverses of `DynResidue`s using Bernstein-Yang.
=> Add `DynResidueInverter`

src/modular/dyn_residue/inv.rs, src/traits.rs, src/traits/sealed.rs, src/uint.rs, src/uint/macros.rs
This trait is needed for the Montgomery form types to instantiate a Bernstein-Yang inverter which operates in the Montgomery domain, by passing R^2 as the adjuster.
It's sealed for now, but could be made public if needed (which might be the case for writing generic trait bounds).
It's extracted from the `PrecomputeInverter` trait, where previously the impl for `DynResidueParams` had a `todo!()` about what to do with this method. Splitting it out into a separate trait resolves this issue.
=> Extract sealed `PrecomputeInverterWithAdjuster` trait

src/macros.rs
They're extremely limited and very difficult to use in their current form, and could use some work
=> Unexport `const_assert_*` macros

src/uint/encoding.rs, src/uint/macros.rs
Adds `const fn` encoders which can serialize to big or little endian byte arrays.
=> Uint: `const fn` encoders

src/modular/bernstein_yang.rs
Use `Self::ZERO` as a default value for constructing results, rather than `[0; LIMBS]`.
=> Bernstein-Yang: minor cleanups

src/modular/bernstein_yang.rs, src/modular/bernstein_yang/macros.rs
Extracts `from_uint` and `to_uint` methods onto `Uint62L`, rather than the previous `sat_to_unsat` and `unsat_to_sat` free functions.
Also extracts the `impl_limb_convert!` macro into its own module, which will assist impl'ing a `BoxedUint62L`.
=> Bernstein-Yang: minor refactoring

src/modular/boxed_residue.rs, src/modular/boxed_residue/pow.rs, src/traits.rs, src/uint/boxed/ct.rs, src/uint/boxed/div.rs, src/uint/boxed/inv_mod.rs, src/uint/boxed/neg.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs
We can't impl `subtle::ConditionallySelectable` for `Boxed*` types due to a bound on `Copy`.
I've proposed various ways to try to fix this upstream, e.g. dalek-cryptography/subtle#118, from which the `ConstantTimeSelect` trait has been extracted. It provides the same API as
`ConditionallySelectable` but without the `Copy` bound.
A blanket impl of `ConstantTimeSelect` for all `ConditionallySelectable` types means that all stack allocated types can continue to use `ConditionallySelectable` and will receive an impl of `ConstantTimeSelect` as well.
A bound on `ConstantTimeSelect` has been added to the `Integer` trait as well, allowing it to be used on all `*Uint` types in this crate with `Integer` as the trait abstraction.
=> Add `ConstantTimeSelect` trait

src/const_choice.rs, src/modular/bernstein_yang.rs, src/modular/residue/inv.rs, src/uint/macros.rs
Replaces previous usages of `(_, ConstChoice)` with `ConstCtOption`.
=> Bernstein-Yang: use `ConstCtOption`

src/modular.rs, src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs, src/modular/bernstein_yang/macros.rs, src/uint/boxed/inv_mod.rs
Adds a boxed equivalent of `BernsteinYangInverter` which operates on values whose number of limbs is determined at compile time.
It's largely copy-pasted from the stack-allocated equivalent, but the long-term goal will be to rewrite it to use in-place operations rather than allocating.
=> Add `BoxedBernsteinYangInverter`

benches/boxed_residue.rs, src/modular/bernstein_yang/boxed.rs, src/modular/boxed_residue/inv.rs, src/uint/boxed.rs, src/uint/mul.rs
Even without any optimization work, it seems significantly faster:
```
Montgomery arithmetic/invert, U256
time:   [6.8324 ms 6.8402 ms 6.8482 ms]
```
```
Montgomery arithmetic/Bernstein-Yang invert, U256
time:   [342.58 µs 343.71 µs 344.81 µs]
```
=> `BoxedResidueInverter` tests and benchmarks

src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs
```
Montgomery arithmetic/Bernstein-Yang invert, U256
time:   [289.83 µs 290.75 µs 291.70 µs]
change: [-17.320% -16.859% -16.379%] (p = 0.00 < 0.05)
```
=> BoxedBernsteinYangInverter: reduce allocations

src/uint/boxed.rs, src/uint/boxed/from.rs
=> BoxedUint: move `From` impls to module

src/modular/bernstein_yang/boxed.rs, src/modular/boxed_residue.rs, src/uint/boxed.rs, tests/bernstein_yang_proptests.rs, tests/boxed_residue_proptests.rs
Adds proptests for the P-256 modulus analogous to the ones we have for `BernsteinYangInverter`.
=> `BoxedBernsteinYangInverter` proptests

benches/uint.rs, src/modular.rs, src/modular/dyn_residue.rs, src/modular/residue/macros.rs, src/uint/boxed/mul_mod.rs, src/uint/div.rs, src/uint/mul_mod.rs
These functions operate in variable time with respect to the `rhs` parameter.
Renames them to `*_vartime` as is the convention of this crate, and in their place adds an actual constant-time remainder implementation (using `div_rem`)
=> Uint: rename `rem(_wide)` => `rem(_wide)_vartime`

src/modular/bernstein_yang.rs, src/uint.rs, src/uint/gcd.rs, tests/uint_proptests.proptest-regressions, tests/uint_proptests.rs
Adds support for computing the greatest common divisor of two numbers using the Bernstein-Yang algorithm, which is already impl'd for inversions.
=> Add `Uint::gcd` using Bernstein-Yang

src/modular/bernstein_yang.rs, src/uint/gcd.rs
All the prerequisites are there. It was simply an oversight not making it so in #472.
=> Make `Uint::gcd` a `const fn`

src/uint/gcd.rs, tests/uint_proptests.rs
Since Bernstein-Yang relies on `f` being odd, this makes `Uint::gcd` return a `ConstCtOption` rather than panicking in the event that `f` is even.
=> Uint: make GCD fallible

benches/dyn_residue.rs, src/modular/dyn_residue/inv.rs, tests/dyn_residue_proptests.rs
This results in a massive performance improvement:
```
Montgomery arithmetic/invert, U256
time:   [1.7834 µs 1.7870 µs 1.7913 µs]
change: [-99.974% -99.974% -99.974%] (p = 0.00 < 0.05)
```
=> Impl `DynResidue::inv(ert)` using Bernstein-Yang

src/modular/residue.rs, src/modular/residue/inv.rs, src/modular/residue/macros.rs, tests/residue.rs
Adds an initial set of proptests which cover inversions, similar to the ones recently added to `DynResidue`.
=> Residue: add proptests

src/const_choice.rs, src/lib.rs, src/limb/add.rs, src/limb/mul.rs, src/limb/sub.rs, src/modular/boxed_residue/mul.rs, src/modular/reduction.rs, src/primitives.rs, src/uint/boxed/mul_mod.rs, src/uint/div_limb.rs, src/uint/mul.rs, src/uint/mul_mod.rs
=> Move various operations on Words to a new `primitves` module

src/modular/bernstein_yang.rs
Adds some basic tests for `Int62L` arithmetic
=> Bernstein-Yang: add `Int62L` arithmetic tests

src/limb.rs, src/modular/residue/macros.rs, src/non_zero.rs, src/uint.rs, src/uint/div.rs, src/uint/sqrt.rs
Replaces the previous type-specific `NonZero::const_new` methods with more idiomatic `Limb::to_nz`/`Uint::to_nz` methods which can be called on a value and return `ConstCtChoice<NonZero<_>>`.
=> Use `{Limb, Uint}::to_nz` to convert to `NonZero`

src/non_zero.rs
The `NonZero::from_uint` method duplicates the `Uint::to_nz` method, and isn't actually used anywhere in this codebase.
Also reorganizes the module to place all the inherent impls at the top, and the trait impls at the bottom.
=> NonZero: remove `from_uint`; reorganize module

src/modular/boxed_monty_form.rs, src/modular/boxed_monty_form/mul.rs, src/modular/monty_form.rs, src/modular/monty_form/mul.rs, src/traits.rs, src/uint.rs, src/uint/boxed.rs
A part of #348 
Fixes #448
All the naming is up for debate (see also #351)
- add `Monty` associated type to `Integer` linking it to the corresponding Montgomery form
- add `Monty` trait with an associated type linking back to the corresponding `Integer` and a bunch of bounds (similar to `Integer`)
- remove the bound on `Square` which made it hard to make `Square` a bound to other traits. This means that there's no default implementation anymore.
- add `SquareAssign` trait.
I will make a separate PR adding `div_by_2()` to `Monty` after #436 is merged
=> Add traits to connect integers and residue represenations

src/const_choice.rs, src/modular/boxed_monty_form.rs, src/modular/div_by_2.rs, src/odd.rs, src/uint/boxed.rs, src/uint/boxed/bits.rs, src/uint/boxed/cmp.rs, src/uint/boxed/div.rs, src/uint/boxed/div_limb.rs, src/uint/boxed/encoding.rs, src/uint/boxed/shl.rs, src/uint/boxed/sqrt.rs, src/uint/div_limb.rs, src/uint/encoding.rs
This is a another continuation of #436 after I lost track of where I overrode the master branch's changes.
=> Expand integer trait

src/modular/boxed_monty_form.rs, src/modular/const_monty_form.rs, src/modular/div_by_2.rs, src/modular/monty_form.rs, src/traits.rs
- add `Monty::div_by_2()` method
- make `MontyForm::div_by_2()` and `ConstMontyForm::div_by_2()` const 
- make the internal `div_by_2()` take an `Odd`-wrapped modulus
Thought about making it a trait (like `Square`), but it's somewhat tied to the Montgomery modulus.
=> Add `div_by_2()` to `Monty` trait

src/modular/boxed_monty_form/inv.rs
Results in a massive performance improvement:
```
Boxed Montgomery arithmetic/invert, U256
time:   [273.74 µs 274.79 µs 275.90 µs]
change: [-95.729% -95.714% -95.696%] (p = 0.00 < 0.05)
```
=> Use Bernstein-Yang for `BoxedMontyForm::invert`

src/modular.rs, src/modular/bernstein_yang/boxed.rs, src/uint/boxed.rs, src/uint/boxed/gcd.rs, tests/boxed_uint_proptests.rs, tests/uint_proptests.rs
Support for computing the greatest common divisor of two `BoxedUint`s using Bernstein-Yang
=> Add `BoxedUint::gcd`

src/traits.rs, src/uint/boxed/gcd.rs, src/uint/gcd.rs, tests/boxed_uint_proptests.rs
Adds a trait for computing the greatest common divisor of two numbers.
Uses a fallible impl for the `*Uint` types, and an infallible one for `Odd<*Uint>`.
=> Add `Gcd` trait

src/modular/boxed_monty_form/inv.rs, src/modular/const_monty_form.rs, src/modular/const_monty_form/inv.rs, src/modular/monty_form/inv.rs, src/traits/sealed.rs, src/uint/boxed/from.rs, src/uint/boxed/inv_mod.rs, src/uint/gcd.rs, src/uint/macros.rs, tests/bernstein_yang_proptests.rs
Moves all of the impls for these traits to `Odd<Uint<_>>`/`Odd<BoxedUint>`.
They infallibly return an inverter, but previously panicked if called on even numbers.
This commit replaces the panic condition with type safety instead.
=> Impl `PrecomputeInterver(WithAdjuster)` on `Odd`

benches/boxed_monty.rs, src/modular/bernstein_yang/boxed.rs
Performs more operations in-place
```
Boxed Montgomery arithmetic/invert, 4096-bit
time:   [208.34 µs 208.70 µs 209.08 µs]
change: [-23.092% -22.837% -22.579%] (p = 0.00 < 0.05)
```
=> Boxed Bernstein-Yang: reduce allocations

Cargo.lock, Cargo.toml, src/traits.rs, src/uint/boxed/div.rs, src/uint/boxed/div_limb.rs, src/uint/div.rs, src/uint/div_limb.rs, tests/boxed_monty_form.rs, tests/boxed_uint_proptests.rs, tests/const_monty_form.rs, tests/monty_form.rs
This is the next step for https://github.com/entropyxyz/crypto-primes/pull/36
- add more bounds on `Monty::Params` (goes in line with the bounds on `Monty` and `Integer`);
- add `From<Limb>` bound for `Integer`;
- use original `num-bigint` instead of `num-bigint-dig` for compatibility with `num-modular` (used in tests); 
- fix some vartime usage in constant time division methods
- add `DivRemLimb` and `RemLimb` traits (and separate `rem_limb()` methods - there's a significant speedup, and these are the ones I actually use in `crypto-primes`)
=> Add `DivRemLimb` and `RemLimb` traits

src/odd.rs, tests/bernstein_yang.rs, tests/boxed_monty_form.rs, tests/boxed_uint.rs, tests/common/mod.rs, tests/const_monty_form.rs, tests/monty_form.rs, tests/uint.rs
Extracts a module containing shared functionality which can be reused between various tests.
Currently it just contains `to_biguint` (which has been adapted to work with both `Uint` and `BoxedUint`)
=> tests: extract `common` module

src/traits.rs, src/uint/boxed/inv_mod.rs, src/uint/inv_mod.rs
Adds a trait for computing modular inverses with the modulus provided as an argument, impl'd for both `Uint` and `BoxedUint`.
=> Add `InvMod` trait

benches/monty.rs, src/modular/monty_form.rs, src/modular/monty_form/add.rs, src/modular/monty_form/inv.rs, src/modular/monty_form/sub.rs, src/uint/mul_mod.rs, tests/monty_form.rs, tests/uint.rs
For consistency with `BoxedMontyParams::new_vartime` and our general labeling strategy.
=> Rename `MontyParams::new` => `::new_vartime`

benches/boxed_monty.rs, src/modular/boxed_monty_form.rs, src/modular/monty_form.rs, tests/boxed_monty_form.rs, tests/monty_form.rs
Notably `Odd` permits a simple reference conversion to `NonZero` which makes it possible to clean up some tests.
=> Have `(Boxed)MontyParams::modulus` return `&Odd<_>`

src/modular/monty_form.rs, tests/monty_form.proptest-regressions, tests/monty_form.rs
Adds a constant-time equivalent to `MontyParams::new_vartime`
=> Add constant-time `MontyParams::new`

src/const_choice.rs, src/traits.rs, src/uint.rs, src/uint/bits.rs, src/uint/boxed.rs, src/uint/boxed/bits.rs, src/uint/boxed/sqrt.rs
- Add a trait for various bit counting/setting operations. Some were moved from the `Integer` trait.
- Extract the implementations of various methods into functions acting on `&[Limb]`, to be shared between `Uint` and `BoxedUint`.
=> Add `BitOps` trait

benches/monty.rs
The vartime constructor is 2.75X faster:
```
Dynamic Montgomery arithmetic/MontyParams::new
time:   [5.8611 µs 5.8708 µs 5.8812 µs]
Dynamic Montgomery arithmetic/MontyParams::new_vartime
time:   [2.1284 µs 2.1405 µs 2.1567 µs]
```
=> Add benchmarks for `MontyParams::new`

benches/boxed_monty.rs, benches/boxed_uint.rs, src/odd.rs, src/traits.rs, src/uint/boxed/rand.rs, src/uint/boxed/sqrt.rs, src/uint/rand.rs
Adds a trait for generating a random number of a given bit size.
Can be improved by using masking instead of shift.
- Is there a better way to express this API?
- Should it be constant-time in `bit_length`? 
- Should the inherent `BoxedUint::random()` take `bits_precision` as well?
=> Add `RandomBits` trait

src/lib.rs
Provide a more comprehensive overview of the main types in the crate
=> rustdoc: rewrite "Usage" intro

src/const_choice.rs, src/uint/inv_mod.rs
This is an oversight from #501 which switched to using Bernstein-Yang inversions for `Uint::inv_odd_mod`.
The new implementation in #501 assumes `s` is always `Odd` but didn't actually check for that and set the `ConstCtOption` to be "none" accordingly. This PR fixes that.
=> Handle even `s` in `Uint::inv_mod`

src/modular/boxed_monty_form.rs, src/modular/monty_form.rs, src/traits.rs
The implementation for `Uint` was already vartime. The `BoxedUint` one wasn't, changed to vartime.
It would be logical to have `new_params()` for the constant-time implementation, but implementing it for `Uint` requires additional bounds with `Split`/`Concat` which have to be propagated everywhere. Not sure what the best course of action here is.
One possibility is perhaps splitting out the "convertible to Montgomery" in a separate trait.
=> Add "vartime" suffix to Monty::new_params()

src/modular.rs, src/modular/monty_form.rs, src/traits.rs, src/uint/concat.rs, src/uint/from.rs, src/uint/macros.rs, src/uint/mul.rs, src/uint/split.rs
Changes to a "little endian" `lo, hi` convention for the ordering of arguments to concatenation methods and the ordering of the returned 2-tuple from split methods.
This is more consistent with the rest of the crate, and the `Uint { limbs }` array which uses a little endian ordering.
Closes #519
=> Reverse `Concat(Mixed)`/`Split(Mixed)` argument ordering

src/lib.rs
It has been removed in recent Rust releases, and replaced with a printed warning:
https://github.com/rust-lang/rust/pull/103877
=> Remove docs about `const_eval_limit`

src/uint/macros.rs
It wasn't updated to reflect the low/high ordering changes from #526
=> Uint: fix macro-generated concat/split docs

src/uint/inv_mod.rs
It's really an implementation detail of the Bernstein-Yang inverter, and not actually customizable by the caller, so get it out of the way.
=> Uint: remove `UNSAT_LIMBS` from `inv_*mod`

src/uint/mul.rs
This parameter is inferred via `Concat<Output = Uint<WIDE_LIMBS>`.
=> Move `Uint::square` const param `WIDE_LIMBS` to impl block

src/modular/boxed_monty_form.rs, src/modular/monty_form.rs, src/traits.rs, src/uint.rs, src/uint/boxed.rs
- Add `Integer::from_limb_like()`, `one_like()`, and `Zero::zero_like()`. This is needed in [#39](https://github.com/entropyxyz/crypto-primes/pull/39)
- Add `Monty::params()` and `as_montgomery()` 
I do not entirely like `from_limb_like`, but that's all I could come up with.
=> Additional methods for `Integer` and `Monty`

src/modular/monty_form.rs
Moves the `const WIDE_LIMBS` generic parameter from `MontyParams::new` to the outer scope, since it's intended to be inferred via the `Concat` trait rather than explicitly specified.
=> MontyParams: refactor const generic `WIDE_LIMBS` parameter

src/uint.rs, src/uint/boxed.rs
It's safer to use explicit types than to let the compiler infer them in these situations
=> Use explicit types in pointer casts

src/uint/div.rs, tests/uint.rs
Adds a few usage examples for div operations. ref issue #283.
Additionally modifies:
```rust
pub const fn wrapping_rem
```
into:
```rust
pub const fn wrapping_rem_vartime
```
since it uses ```rem_vartime``` internally.
=> docs: a few usage examples for div

benches/boxed_uint.rs, src/uint/boxed/sqrt.rs
Removed one of the inline TODO's for reducing allocation. Also added some benchmarks.
I am not sure if it's more appropriate to use `.clone_from` on `BoxedUint` or the limbs; it seems like alloc-free cloning is done on the limbs elsewhere. Reviewer please advise.
Interestingly the benchmarks did not show statistically significant improvements between the code change. I am not aware of benchmarking on memory usage, either.
=> Boxed sqrt reduce cloning

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, src/array.rs, src/lib.rs, src/non_zero.rs, src/uint.rs, src/uint/array.rs, src/uint/encoding.rs, src/uint/encoding/der.rs
This commit replaces the optional `generic-array` feature with `hybrid-array`, which adds support for (de)serializing `Uint`s as `hybrid_array::Array<u8, _>`.
The `hybrid_array` crate notably has significantly less unsafe code than `generic-array`, which it accomplishes by being built on const generic core arrays, which are the public inner type of `Array`.
=> Migrate from `generic-array` to `hybrid-array`

src/limb.rs, src/modular/const_monty_form.rs, src/traits.rs, src/uint.rs
Renames the trait to match the prospective name it might potentially receive upstream in `num-traits`: rust-num/num-traits#303
=> Rename `ZeroConstant` => `ConstZero`

tests/uint.rs
Some formatting changes, and also test bitwise ops regardless of if the rhs param is zero (appears to be copypasta from division tests).
=> Cleanup `Uint` tests

src/uint/shl.rs, src/uint/shr.rs, tests/uint.proptest-regressions, tests/uint.rs
The amount to shift was being miscomputed. It should've been a saturating-like operation, where any shift larger than the precision returns zero, but instead a modulus (which isn't constant time) was being applied instead.
This also adds proptests to ensure correct behavior.
=> Fix `Uint::shr(_vartime)` and `Uint::shl(_vartime)`

src/uint/shl.rs, src/uint/shr.rs
Adds panicking wrappers for `overflowing_sh*_vartime` which panic-on-overflow.
=> Add `Uint::{shl_vartime, shr_vartime}`

.github/workflows/crypto-bigint.yml, .github/workflows/dudect.yml
It takes awhile to run, especially if we expand it.
If it's in its own workflow we can skip running it on PRs, but still run it on merges, which should retroactively detect any regressions.
=> CI: move `dudect` into its own workflow

src/uint/macros.rs
Previously only `Uint::to_be_bytes` was defined this way.
=> Add a `const fn` version of `Uint::to_le_bytes`

.github/workflows/crypto-bigint.yml
`cargo careful` is a tool to run your Rust code extra carefully -- opting into a bunch of nightly-only extra checks that help detect Undefined Behavior, and using a standard library with debug assertions.
https://github.com/RalfJung/cargo-careful
=> CI: test with `cargo-careful`

Cargo.lock, Cargo.toml, src/uint/rand.rs
This was supposed to be a "backwards compatible" release but it did wind up adding some trait impls which break inference in certain cases.
This bumps the dependency and fixes the ambiguities.
=> Bump `hybrid-array` to v0.2.0-rc.1

Cargo.lock, Cargo.toml, src/modular/const_monty_form.rs, src/traits.rs
Added in rust-num/num-traits#303
=> Use `ConstZero` trait from `num_traits`

src/uint/bit_xor.rs
There was a documentation typo. Now it is gone!
=> Fix documentation nit

src/uint/div.rs
Improvements are made to the main loop of `div_rem` and `div_rem_vartime`.
- `r` as a result of subtraction with borrow does not need to be mutable because it is not strictly speaking modified afterwards.
- The declaration of `from_word_mask` is done twice in a similar way each time through the loop, a performance gain can be found by making a single declaration for this choice, to be reused in the two calls.
=> Some efficiency improvements in `div_rem`

src/uint/mul_mod.rs
This pull request implements a small refactoring in the `mac_by_limb` function to streamline the multiplication and accumulation operations (`mul_mod`) by avoiding unnecessary intermediate variable declarations within the `while` loop.
=> Small refactoring in mul mod

src/uint/boxed/inv_mod.rs
This PR addresses #591 by porting the implementation of `InvMod` from `Uint` into `BoxedUint`. The relevant unit tests from `uint/inv_mod.rs` are also ported over to `uint/boxed/inv_mod.rs`
=> Boxed inv even mod

src/lib.rs
Originally added in #119 along with dudect support, however it was incomplete.
This is now triggering warnings on the latest nightly versions.
=> Remove vestigial sidefuzz support

src/limb.rs, src/uint.rs, src/uint/boxed.rs, src/uint/encoding.rs
This was only implemented for `Wrapping<T>` and `NonZero<T>` (where T: Binary).
=> Add impls for fmt::Binary

src/odd.rs
Most other wrapper types implement serde, e.g. `NonZero` and `Wrapping`. This PR implements it for `Odd` as well.
One oddity I noticed when writing the tests was that deserializing a bigger `Uint` into a smaller one does not return an error. Instead the original value seems to be truncated to fit the smaller type. Is that the expected behaviour?
=> Implement serde for `Odd`

src/macros.rs, src/uint/macros.rs
The previous calculation of the number of unsaturated 62-bit limbs needed to represent an integer of a given size was incorrect, leading to miscomputed results as seen in #606.
This commit switches to a much simpler calculation based on `div_ceiling(62)`, and also adds a const assertion that the computed number of limbs is sufficient to hold a `$bits`-sized integer.
=> Fix `bernstein_yang_nlimbs!` calculation

Cargo.lock
Updates the following dependencies:
$ cargo update
Updating crates.io index
Locking 70 packages to latest compatible versions
Updating aho-corasick v1.1.2 -> v1.1.3
Updating anstyle v1.0.4 -> v1.0.7
Updating autocfg v1.1.0 -> v1.3.0
Removing bitflags v1.3.2
Removing bitflags v2.4.1
Adding bitflags v2.5.0
Updating bumpalo v3.14.0 -> v3.16.0
Updating bytes v1.5.0 -> v1.6.0
Updating ciborium v0.2.1 -> v0.2.2
Updating ciborium-io v0.2.1 -> v0.2.2
Updating ciborium-ll v0.2.1 -> v0.2.2
Updating clap v4.4.8 -> v4.5.7
Updating clap_builder v4.4.8 -> v4.5.7
Updating clap_lex v0.6.0 -> v0.7.1
Updating crossbeam-deque v0.8.3 -> v0.8.5
Updating crossbeam-epoch v0.9.15 -> v0.9.18
Updating crossbeam-utils v0.8.16 -> v0.8.20
Adding crunchy v0.2.2
Updating either v1.9.0 -> v1.12.0
Updating errno v0.3.7 …
=> Cargo.lock: bump deps

src/uint/gcd.rs, tests/uint.rs
Uses a similar method to `Uint::inv_mod` for extending `Uint::gcd` with support for an even modulus, first dividing out `2^k` from both operands where this operation will ensure at least one value is odd, and then applying Bernstein-Yang to the odd modulus, multiplying the result by `2^k`.
=> Add support for computing `Uint::gcd` with even modulus

src/uint/gcd.rs, tests/uint.rs
See also: #618
The computation was previously fallible because even values were unsupported.
Now that they're supported, the computation no longer needs to be fallible.
We can eventually remove `type Output` from the `Gcd` trait after a similar treatment is applied to `BoxedUint` (see #618).
=> Make `Uint::gcd` calculation infallible

src/traits.rs, src/uint/boxed/gcd.rs, tests/boxed_uint.rs
Edit: it works now! Uses an implementation similar to `Uint::gcd` as added in #617
~~Tests are currently failing due to the handling of zero as one of the values.~~
~~I'm thinking the return value of `CtOption` is largely a vestige of when even numbers weren't supported, and we can change it to be infallible now, similar to `num-bigint`.~~
~~I'm uncertain why we aren't seeing similar failures in the `Uint::gcd` proptests as I expect it to have a similar issue.~~
=> Add support for computing `BoxedUint::gcd` with even modulus

src/odd.rs
The `Odd` wrapper type does not implement the same
traits as it's sibling `NonZero`. This PR attempts
to rectify that and make them more similar.
In particular the PR implements:
- `ConstantTimeEq`
- `zeroize::Zeroize`
- `fmt::Display`
- `fmt::Binary`, `fmt::Octal`, `fmt::LowerHex`, `fmt::UpperHex`
=> Implement a few more traits for `Odd`

src/non_zero.rs
Makes it so users can have `NonZero` constants.
=> Add a const_new method to NonZero

src/lib.rs, src/traits.rs, src/uint/boxed/encoding.rs, src/uint/encoding.rs
This adds fallible parsing for binary, decimal, and hex integers (and any base from 2 to 36).
The format of these numbers generally matches the `from_str_radix` methods of the standard library. One exception is that underscores may used as spacers, as in `+1_000_000` for example. This is consistent with the `num_bigint` crate.
The `DecodeError` enum is promoted from the uint.boxed module and reused.
=> Implement `from_str_radix_vartime` for `Uint`, `BoxedUint`

Cargo.lock, src/uint/mul_mod.rs, tests/uint.rs
The previous `mul_mod` was variable-time with respect to the modulus. This adds a proper constant-time version.
It also changes the `p` argument to be `NonZero<Self>`
=> Split `Uint::mul_mod` and `Uint::mul_mod_vartime`

benches/uint.rs, src/uint/div.rs, src/uint/div_limb.rs
Implements faster vartime division (vartime with the divisor only) for Uint<L> based on Knuth's TAOCP volume 2, as outlined at https://janmr.com/blog/2014/04/basic-multiple-precision-long-division/
This does not address vartime division for BoxedUint or the other TODOs in https://github.com/RustCrypto/crypto-bigint/pull/511
Relevant benchmarks:
```
wrapping ops/div/rem_vartime, U256/U128, full size
time:   [84.091 ns 84.290 ns 84.525 ns]
change: [-85.312% -85.155% -84.896%] (p = 0.00 < 0.05)
wrapping ops/rem_vartime, U256/U128, full size
time:   [84.129 ns 84.474 ns 84.890 ns]
change: [-84.208% -84.057% -83.898%] (p = 0.00 < 0.05)
wrapping ops/rem_wide_vartime, U256
time:   [166.95 ns 167.27 ns 167.69 ns]
change: [-94.750% -94.705% …
```
=> Faster vartime division for Uint

benches/boxed_uint.rs, src/uint/boxed/div.rs, src/uint/boxed/div_limb.rs
This implements the division algorithm from #608 for `BoxedUint`. It includes some adjustments to `div_rem_limb_with_reciprocal` and `rem_limb_with_reciprocal` to reduce allocations.
The main body of the division is implemented as a helper method `div_rem_vartime_in_place`. This is partly to allow internal reuse in implementing `to_str_radix_vartime`.
=> Faster vartime division for BoxedUint

src/non_zero.rs, src/primitives.rs, src/uint/boxed/mul_mod.rs, src/uint/div_limb.rs, src/uint/mul_mod.rs
As mentioned in #511, `mul_rem()` is currently variable-time in `d`, which makes `mul_mod_special()` variable-time in `c`. This PR makes `mul_rem()` constant-time with no loss of performance. 
Since `mul_mod` now uses the `div_limb` functionality, it was moved there.
Also added `NonZero::<Limb>::new_unwrap()`.
=> Make `mul_rem()` primitive constant-time

src/const_choice.rs, src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs
Changes `Int64L::is_negative` to return `ConstChoice` rather than `bool`, also adding a `Int64L::select` method for selecting between two values predicated on a `ConstChoice`.
This eliminates some of the branching in the implementation (#627).
cc @erik-3milabs
=> Uint: constant-time Bernstein-Yang `is_negative`

src/const_choice.rs, src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs
Addresses some data-dependent branching and use of `bool` noted in #627
=> Make Bernstein-Yang `Int62L::eq` return `ConstChoice`

src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs
Similar change to #630, which was for `Int62L`.
Addresses some data-dependent branching and use of `bool` noted in #627
=> Bernstein-Yang: have `BoxedInt62L::{is_zero, is_one}` return `Choice`

benches/uint.rs, src/modular/bernstein_yang.rs, src/uint/add.rs, src/uint/gcd.rs, tests/uint.rs
The previous implementation runs in variable-time with respect to `g`. However in the event both inputs are secret a fully constant-time implementation is required.
This implements the method described in section 11 of https://eprint.iacr.org/2019/266.pdf and more specifically this Python code from Figure 11.1:
```python
from divsteps2 import divsteps2
def iterations(d):
return (49*d+80)//17 if d<46 else (49*d+57)//17
def gcd2(f,g):
assert f & 1
d = max(f.nbits(),g.nbits())
m = iterations(d)
delta, fm, gm, P = divsteps2 (m,m+d,1,f,g)
return abs(fm)
def recip2(f,g):
assert f & 1
d = max(f.nbits(),g.nbits())
m = iterations(d)
precomp = Integers(f)((f+1)/2)^(m−1)
delta, fm, gm, P = divsteps2(m,m+1,1,f,g)
V = sign(fm)*ZZ(P[0][1]*2^(m-1))
return ZZ(V*precomp)
```
Instead of bounding the loop …
=> Initial constant-time stack-allocated Bernstein-Yang

src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs, src/uint/boxed/gcd.rs
The previous implementation runs in variable-time with respect to `g`. However in the event both inputs are secret a fully constant-time implementation is required.
This implements Bernstein-Yang in constant-time with respect to both parameters by computing a worst case number of iterations for the algorithm to converge, partially sharing the implementation with #632.
=> Constant-time heap-allocated Bernstein-Yang

Cargo.toml, src/traits.rs, src/uint/boxed/gcd.rs, src/uint/gcd.rs
Adds a method to the `Gcd` trait for computing greatest common divisor in variable time, permitting a faster implementation.
=> Add `Gcd::gcd_vartime`

src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs
These types are used within the Bernstein-Yang implementation(s) and implements a 62-bit unsaturated form used by the algorithm.
=> Rename `*Int62L` => `*UnsatInt`

src/modular/bernstein_yang.rs, src/modular/bernstein_yang/boxed.rs
The type has been renamed to `UnsatInt`, and the functions to `unsatint`
=> Fix remaining `int62l` references

src/uint/boxed/div.rs, src/uint/div.rs, src/uint/div_limb.rs, tests/uint.rs
Fixes #638 
A special case when the leading dividend word equalled the leading dividend word was not being handled.
=> Fix vartime division edge case

benches/boxed_uint.rs, benches/uint.rs, src/uint/boxed/mul.rs, src/uint/mul.rs
Applying this to BoxedUint results in an almost 50% speedup at 4096 bits.
Also adding benchmarks for multiplication.
=> Move schoolbook squaring implementation into a macro

src/const_choice.rs, src/uint/div_limb.rs
In regards comments on #646, this handles potential overflow in the remainder value.
=> Handle remainder as a wide word in div3by2

src/modular/bernstein_yang/boxed.rs, src/uint/boxed/gcd.rs
The PR currently has just a testcase illustrating the problem. 
So the question is, what should the behavior be? We can equalize the sizes of the arguments at the top level, but that would make `gcd()` not constant time wrt numbers of limbs. Then again, would users assume that it is?
=> Support `BoxedUint::gcd(_vartime)` where `self` and `rhs` have a different number of limbs

src/modular/bernstein_yang/boxed.rs, src/uint/boxed/gcd.rs
Implicitly widens inputs to the size of the largest before computing Bernstein-Yang for GCD.
=> Bernstein-Yang: support boxed GCD with different size inputs

src/uint/boxed/add.rs
Adds `Add` impls for `BoxedUint` for the following `rhs` types:
- `Uint<LIMBS>`
- `u8`
- `u16`
- `u32`
- `u64`
- `u128`
The primitive integer types convert to `Uint<LIMBS>` then leverate the `Add` impl for that.
See also: #585
=> BoxedUint: `Add` impls for stack allocated types

src/modular/bernstein_yang/boxed.rs, src/modular/bernstein_yang/macros.rs
Adds a `BoxedUnsatInt::from_uint_widened` constructor which can be used to pad all `BoxedUnsatInt`s used as parameters to Bernstein-Yang to the same size at allocation time, rather than retroactively widening them to be the same size which may incur an additional allocation.
=> Bernstein-Yang: boxing optimizations

benches/uint.rs, src/limb/shl.rs, src/non_zero.rs, src/uint/boxed/div.rs, src/uint/boxed/shl.rs, src/uint/boxed/sqrt.rs, src/uint/div.rs, src/uint/shl.rs, src/uint/sqrt.rs
This replaces the `div_rem` method for Uint and BoxedUint with one based on the updated vartime division method.
Unlike the old method, this one panics if `NonZero(0)` is given as the divisor. The `sqrt` method relied on the old behavior and is updated.
The `Default` implementation of `NonZero` was also producing invalid `NonZero(0)` values, which affected the `NonZero::map` usage in `checked_div`. The trait implementation is updated to return `Self::ONE` as the default.
Some relevant benchmarks:
```
wrapping ops/div/rem, U256/U128, full size
time:   [312.41 ns 314.29 ns 317.18 ns]
change: [-81.412% -79.729% -78.416%] (p = 0.00 < 0.05)
wrapping ops/rem, U256/U128, full size
time:   [310.37 ns 312.08 ns 315.15 ns]
change: [-78.497% -78.170% -77.896%] (p = 0.00 < …
```
=> Faster constant-time division

src/uint/boxed/div.rs, src/uint/div.rs, src/uint/div_limb.rs
- Extract shl/shr by a limb-sized shift into separate methods
- Add a more detailed docstring and some debug assertions in `div3by2()`
- Replaced `saturating_sub` with `wrapping_sub` in several places. While logically it is the same thing (the wrapping/saturation only happens for values that are later selected out), I think there are readability advantages. First, elsewhere in the code we use wrapping ops for selected out values (meaning "perform the subtraction without any checks, since we already have a constant-time condition for that"), so `saturating_sub` indicates that the algorithm actually uses the saturation mechanic. Second, in case of a bug, it will be easier to spot the consequences of a "0xffff..." value than a 0.
Questions:
- should I move the new shl/shr methods to …
=> Some simplifications of vartime division

src/uint/boxed/div.rs, src/uint/div.rs, src/uint/div_limb.rs
This reverts commit e7d3b16dd4fc377b4de963f16ab845a2cce185ee.
This needs changes as upstream diverged: https://github.com/RustCrypto/crypto-bigint/actions/runs/10472862474/job/29003356626
=> Revert "Some simplifications of vartime division (#646)"

src/uint/boxed/div.rs, src/uint/div.rs, src/uint/div_limb.rs
This is a fix of reverted #646 
- Extract shl/shr by a limb-sized shift into separate methods
- Add a more detailed docstring and some debug assertions in `div3by2()`
- Replaced `saturating_sub` with `wrapping_sub` in several places. While logically it is the same thing (the wrapping/saturation only happens for values that are later selected out), I think there are readability advantages. First, elsewhere in the code we use wrapping ops for selected out values (meaning "perform the subtraction without any checks, since we already have a constant-time condition for that"), so `saturating_sub` indicates that the algorithm actually uses the saturation mechanic. Second, in case of a bug, it will be easier to spot the consequences of a "0xffff..." value than a 0.
Update:
- Use `div2by1` …
=> Some simplifications of vartime division (second attempt)

src/modular/const_monty_form.rs, src/traits.rs
This is a `nightly`-only lint but it caught some rustdoc comments which are too long and needed to be broken up with more newlines.
=> Fix `clippy::too_long_first_doc_paragraph` violations

benches/uint.rs, src/uint/mul_mod.rs
Also adds benchmarks for Uint modular multiplication.
=> Use `rem_wide_vartime` in `Uint::mul_mod_vartime`

benches/boxed_monty.rs, benches/const_monty.rs, benches/monty.rs, src/limb/shl.rs, src/modular/add.rs, src/modular/boxed_monty_form.rs, src/modular/boxed_monty_form/add.rs, src/modular/boxed_monty_form/neg.rs, src/modular/const_monty_form/add.rs, src/modular/const_monty_form/neg.rs, src/modular/monty_form/add.rs, src/modular/monty_form/neg.rs, src/uint/add_mod.rs, src/uint/boxed/add_mod.rs, src/uint/boxed/shl.rs, src/uint/boxed/sub_mod.rs, src/uint/shl.rs
- Adds benchmarks for Montgomery arithmetic methods
- Adds a `double` method for Montgomery forms and `double_mod` method for Uint/BoxedUint, using a left shift instead of adding `self`
- Uses the existing (faster) `neg_mod` methods in Montgomery form `neg` methods
- Optimizes `add_mod` and `sub_mod` for `BoxedMontyForm` to remove allocations
=> Montgomery form arithmetic improvements

benches/boxed_monty.rs, benches/const_monty.rs, src/limb/cmp.rs, src/modular.rs, src/modular/boxed_monty_form.rs, src/modular/boxed_monty_form/lincomb.rs, src/modular/const_monty_form.rs, src/modular/const_monty_form/lincomb.rs, src/modular/const_monty_form/macros.rs, src/modular/lincomb.rs, src/modular/monty_form.rs, src/modular/monty_form/lincomb.rs, src/uint/boxed/sub_mod.rs
This PR implements Algorithm 2 (for B=1) from Efficient Algorithms for Large Prime Characteristic Fields and Their Application to Bilinear Pairings by Patrick Longa: https://eprint.iacr.org/2022/367
This algorithm interleaves schoolbook multiplication and accumulation of multiple terms with the Montgomery reduction. For moduli with one or more leading zeros, this helps to reduce the number of reductions performed. In the `BoxedUint` case this also reduces the number of allocations required. For larger moduli it may be useful to explore the use of larger values of B along with the existing Karatsuba multiplication.
As a concrete example, the calculation of `(a•b + c•d) mod m` using `ConstMontyForm`, where `m` is a `U256` with at least one leading zero, is reduced from 50 to 32ns in my …
=> Add efficient linear combination for Montgomery forms

src/modular/boxed_monty_form.rs
Support for constructing boxed params from `ConstMontyParams`.
Closes #593
=> Add `BoxedMontyParams::from_const_params`

.github/workflows/crypto-bigint.yml, Cargo.lock, Cargo.toml, README.md
This version leverages the new `core::error::Error` stabilization.
We plan on bumping MSRV to 1.83 before a final release to get the `const_mut_refs` stabilization (#667), so this is something of an interim bump.
=> Bump `hybrid-array` to v0.2.0-rc.10; MSRV 1.81

Cargo.toml, src/lib.rs, src/modular/boxed_monty_form.rs, src/traits.rs
Now that the MSRV is 1.81, use `core::error::Error` instead of `std::error::Error`.
Since this was our only dependency on `std`, we can also remove the entire `std` feature.
=> Remove `std` feature; leverage `core::error::Error`

src/uint/cmp.rs
This PR fixes the documentation for `Uint` comparison. This documentation currently indicates that both [`Uint::lt`](https://github.com/RustCrypto/crypto-bigint/blob/1c946074e6a7f589cf89e3c91448d0068d730a88/src/uint/cmp.rs#L57) and [`Uint::gt`](https://github.com/RustCrypto/crypto-bigint/blob/1c946074e6a7f589cf89e3c91448d0068d730a88/src/uint/cmp.rs#L67) return truthy if the operands are equal. However, included tests for both [`Uint::lt`](https://github.com/RustCrypto/crypto-bigint/blob/1c946074e6a7f589cf89e3c91448d0068d730a88/src/uint/cmp.rs#L227-L229) and [`Uint::gt`](https://github.com/RustCrypto/crypto-bigint/blob/1c946074e6a7f589cf89e3c91448d0068d730a88/src/uint/cmp.rs#L208-L210) show that this is not the case.
Closes #682.
=> docs: fix comparison documentation

src/uint/div.rs
While working in `crypto-primes` I noticed that one of the benchmarks was hanging. The benchmark in question is finding 128 bit primes but returns them in a 256 bit wide uint.
I have reduced the problem somewhat to commit e948539b in `crypto-bigint` and the operations required for [`MontyParams::new_vartime`](https://github.com/RustCrypto/crypto-bigint/blob/master/src/modular/monty_form.rs#L81). 
In particular the problem is somewhere in [`rem_wide_vartime`](https://github.com/RustCrypto/crypto-bigint/blob/master/src/uint/div.rs#L320) which doesn’t treat the lower operand correctly for some rhs values. 
This PR contains a failing test that illustrates the problem.
=> rem_wide_vartime broke in rc.3

src/modular/boxed_monty_form.rs, src/modular/lincomb.rs, src/modular/monty_form.rs, src/modular/monty_form/lincomb.rs, src/traits.rs
This changes the signature of `MontyForm::lincomb_vartime` to take references, for consistency with `BoxedMontyForm` and the trait method. `ConstMontyForm` I've left with owned values, as changing to references seems to have a 15% performance penalty on the benchmark.
=> Add `double` and `lincomb_vartime` methods to `Monty` trait

src/macros.rs, src/uint/div.rs, src/uint/rand.rs
Fixes clippy warnings about `div_ceil` which are appearing on recent nightlies
=> Leverage `div_ceil`

src/uint/boxed/div.rs, src/uint/encoding.rs
Followup to #688 which uses `div_ceil` in feature-gated code, which was missed before
=> Further leverage `div_ceil`

src/macros.rs, src/modular/monty_form/pow.rs
These were half-baked and cause weird compile errors in several situations.
We'll be better off with const support for `assert_eq`/`assert_ne` whenever that lands.
=> Remove `const_assert_*`

.github/workflows/crypto-bigint.yml, Cargo.toml, README.md, src/modular/reduction.rs, src/uint/mul.rs
Replaces macro-based code sharing between the stack-allocated and heap-allocated `*Uint` types with `const fn` using `const_mut_refs`.
Stabilization of this feature is (hopefully) imminent and the PR to do so is in FCP: https://github.com/rust-lang/rust/pull/129195
I will keep this a draft until the feature has actually been stabilized and made it into a stable Rust release.
Edit: stabilization is currently slated for the [1.83.0](https://github.com/rust-lang/rust/milestone/125) milestone, which is set to be released on November 28th, 2024.
=> Leverage `const_mut_refs`; MSRV 1.83

src/modular/monty_form.rs
After discussion in #704, it seemed prudent to add zeroizing support for `MontyParams`, and to use this when zeroizing `MontyForm` as well. This PR adds such support.
Closes #704.
=> Add zeroizing support for `MontyParams`

src/lib.rs, src/limb/rand.rs, src/modular/const_monty_form.rs, src/non_zero.rs, src/odd.rs, src/traits.rs, src/uint/boxed/rand.rs, src/uint/rand.rs, src/wrapping.rs
Relaxes `CryptoRngCore` requirement to `RngCore`. Fixes #137
=> Require `RngCore` instead of `CryptoRngCore` for various random methods

src/modular/boxed_monty_form.rs
As a follow-up to #706, this PR (mostly) adds boxed Montgomery `Zeroize` support. Specifically, it zeroizes the value for `BoxedMontgomeryForm`, but leaves the parameters alone since they're wrapped in an `Arc`. This caveat is carefully documented.
=> Add boxed Montgomery zeroizing support

src/non_zero.rs, src/traits.rs, src/uint/boxed/rand.rs, src/uint/rand.rs
Recent work in #710 relaxes the trait bound for random number generators. This means that functions generating random values using rejection sampling are no longer guaranteed not to leak anything about output values. This PR updates the documentation to make this clear.
=> Update documentation for random functionality

.github/workflows/crypto-bigint.yml, .github/workflows/dudect.yml, .github/workflows/security-audit.yml
My IDE reports that certain branch and path specifications in the GitHub actions configurations are not strictly valid YAML. This PR fixes accordingly.
=> Fix workflow YAML syntax

src/modular/boxed_monty_form.rs, src/modular/const_monty_form/macros.rs, src/modular/monty_form.rs, src/modular/monty_form/lincomb.rs
=> Fix modulus leading zeros calculation for (Boxed)`MontyForm`

.github/workflows/security-audit.yml
It was previously using a very outdated version of the abandoned `actions-rs/audit-check`.
This updates to the latest version with Cargo.lock V4 support.
=> CI: use latest `rustsec/audit-check` for security audit

Cargo.lock, Cargo.toml
NOTE: this release includes breaking changes to the wire format. See RustCrypto/formats#1631
=> Bump `serdect` dependency to v0.3

src/traits.rs, src/uint/boxed/add.rs, src/uint/boxed/mul.rs, src/uint/boxed/sub.rs, src/uint/mul.rs, src/uint/sub.rs
Adds `Add`/`Mul`/`SubAssign` bounds for `Integer`; also adds:
- `impl Add<BoxedUint> for &BoxedUint`
- `impl AddAssign<BoxedUint> for BoxedUint`
- `impl AddAssign<&BoxedUint> for BoxedUint`
- `impl MulAssign<BoxedUint> for BoxedUint`
- `impl MulAssign<&BoxedUint> for BoxedUint`
- `impl Sub<BoxedUint> for &BoxedUint`
- `impl SubAssign<BoxedUint> for BoxedUint`
- `impl SubAssign<&BoxedUint> for BoxedUint`
- `impl<const LIMBS: usize, const RHS_LIMBS: usize> MulAssign<Uint<RHS_LIMBS>> for Uint<LIMBS>`
- `impl<const LIMBS: usize, const RHS_LIMBS: usize> MulAssign<&Uint<RHS_LIMBS>> for Uint<LIMBS>`
- `impl<const LIMBS: usize> SubAssign<Uint<LIMBS>> for Uint<LIMBS>`
- `impl<const LIMBS: usize> SubAssign<&Uint<LIMBS>> for Uint<LIMBS>`
=> Add `Add`/`Mul`/`SubAssign` bounds for `Integer`

src/uint.rs, src/uint/div.rs
Also adds the needed `Div` and `Rem` impls to meet the required bounds
=> Impl `num_traits::Num` for `Uint`

src/traits.rs
Do not provide a default impl for `bits_vartime` so that implementors that do not provide a default impl end up in an infinite loop between `bits_vartime` and `leading_zeros_vartime`.
Fixes #729
=> Fix possibility of infinite loop in BitOps

src/const_choice.rs, src/int/add.rs, src/int/bit_and.rs, src/int/bit_or.rs, src/int/bit_xor.rs, src/int/div.rs, src/int/mul.rs, src/int/neg.rs, src/int/shr.rs, src/int/sub.rs
Minor clean up of existing Int code.
Replaces #722.
=> `Int` - Cleaning up `Int`

src/modular/boxed_monty_form/inv.rs, src/modular/const_monty_form/inv.rs, src/modular/monty_form/inv.rs, src/modular/safegcd.rs, src/modular/safegcd/boxed.rs, src/traits.rs, tests/safegcd.rs
Adds (back) support for computing modular inversions in variable-time with respect to the value being inverted, which computes the specific number of safegcd divsteps to perform based on the input, as opposed to using a worst case number based on the bit length.
Closes #728
=> Variable-time modular inversion support

src/modular/boxed_monty_form/inv.rs, src/modular/monty_form/inv.rs
DRYs out some safegcd init by extracting a `const fn`
=> Modular inversion cleanups

src/const_choice.rs, src/int/add.rs, src/int/bit_and.rs, src/int/bit_or.rs, src/int/bit_xor.rs, src/int/div.rs, src/int/mul.rs, src/int/neg.rs, src/int/shr.rs, src/int/sub.rs, src/uint/mul.rs
- Expand the `Uint::square` operation set 
- Implement `Int::square` operations. 
Replaces #724.
=> `Int` - square operations

src/traits.rs, src/uint/boxed/inv_mod.rs, src/uint/inv_mod.rs
As needed for #737.
This uses a shape similar to the `MulMod` trait.
=> Generic `InvMod`: add `Rhs` param and associated `Output`

src/uint/div.rs
It was previously using `rem_vartime` as introduced in #466. This goes against the "constant time by default" guarantees of this library.
=> Make `Rem` impl on `Uint` constant-time

Cargo.lock, Cargo.toml, src/uint/encoding/der.rs
This unblocks a release by downgrading to the latest stable version so we don't need to wait on a final release of v0.8.
=> Downgrade `der` to v0.7

Cargo.toml
...as opposed to `rand_core/std`, which links the `std` crate
=> Have `rand` feature enable `rand_core/getrandom`

src/int.rs, src/int/inv_mod.rs
Introduces the `Int::inv_mod` operation. 
Replaces #727
=> `Int` - `inv_mod`

src/int.rs, src/int/div_uint.rs, src/int/mul_uint.rs
Introduce interoperability between `Int` and `Uint`. In particular, it enables the multiplication of `Int.mul(Uint)` and `Int.div(Uint)`.
Replaces #726.
=> `Int` - `Int`-`Uint` interoperability

src/int.rs, src/int/gcd.rs, src/uint/gcd.rs
=> `Int` - Gcd

src/traits.rs, src/uint.rs, src/uint/boxed/div.rs, src/uint/div.rs, src/uint/macros.rs, src/uint/mul.rs
Add a `RemMixed` trait in the same vein as `SplitMixed` and `ConcatMixed`, to calculate the remainder of differently sized integers.
Fixes #739.
=> Add a RemMixed trait and impl for Uints

src/modular/boxed_monty_form/pow.rs
Better note why we have to subtract the modulus twice
=> BoxedMontyForm: additional explanatory comments for modpow

src/int.rs, src/uint.rs
While developing #753, we found that `Uint::as_limbs_mut` can be made `const`. This PR introduces this very minor improvement.
=> Make `Uint::as_limbs_mut` const

src/int/rand.rs, src/limb/rand.rs, src/modular/const_monty_form.rs, src/non_zero.rs, src/odd.rs, src/traits.rs, src/uint/boxed/rand.rs, src/uint/rand.rs, src/wrapping.rs
Doesn't matter to us, but allows users to pass `dyn RngCore` args.
=> Add `?Sized` to all `RngCore` bounds

Cargo.lock, Cargo.toml
Note: not for release, that will be `v0.7.0-pre.0`
This sets `master` back to a development branch.
v0.6 development now has its own branch: https://github.com/RustCrypto/crypto-bigint/tree/v0.6
=> Bump version to v0.7.0-pre

Cargo.lock, Cargo.toml, src/int/rand.rs, src/limb/rand.rs, src/modular/const_monty_form.rs, src/non_zero.rs, src/odd.rs, src/traits.rs, src/uint/boxed/rand.rs, src/uint/rand.rs, src/wrapping.rs
This method is to be used by downstream crates:
- https://github.com/RustCrypto/RSA/pull/478
Depends on:
- https://github.com/rust-random/rand/pull/1593
=> provide `RandomMod::try_random_mod` and `Random::try_random` methods

src/modular/reduction.rs, src/uint/mul.rs
Fixes a performance regression introduced in #667. Evidently, compiler relies a lot on knowing the slice sizes at compile time, so I'm inlining `schoolbook_multiplication()`, `schoolbook_squaring()`, and `montgomery_reduction_inner()`, so the compiler can optimize in case of `Uint`s.
Benchmarks:
- `wrapping ops/split_mul, U256xU256` - 26ns to 9ns
- `Const Montgomery arithmetic/multiplication, U256*U256` - 41ns to 21ns
- `Dynamic Montgomery arithmetic/multiplication, U256*U256` - 62ns to 44ns
The effect is less pronounced for longer integers, but sill amounts to 5-10% speedup for U4096.
On a higher level, this affects many `crypto-primes` benchmarks, e.g. doubles the speed of Lucas test for U128.
Possible addition: I think `panic!` in these functions can be replaced with `debug_assert!`, …
=> Inline low level multiplication and reduction functions

src/uint/boxed/add.rs, src/uint/boxed/sub.rs
=> [0.6] Fixup assertion in `AddAssign` and `SubAssign` of `BoxedUint`

benches/monty.rs, src/modular/boxed_monty_form.rs, src/modular/boxed_monty_form/add.rs, src/modular/boxed_monty_form/mul.rs, src/modular/boxed_monty_form/pow.rs, src/modular/boxed_monty_form/sub.rs, src/modular/div_by_2.rs, src/modular/monty_form.rs, src/modular/monty_form/mul.rs, src/modular/reduction.rs, src/modular/safegcd/boxed.rs, src/primitives.rs, src/traits.rs, src/uint/boxed/add_mod.rs, src/uint/boxed/inv_mod.rs, src/uint/boxed/shr.rs, src/uint/boxed/sub.rs, src/uint/inv_mod.rs, tests/boxed_monty_form.rs, tests/boxed_uint.rs
Trying to figure out massive slowdowns `crypto-primes` experiences for boxed uints (up to 4x). Could be the reason of the slowdowns in `RSA` as well. 
Public changes:
- Added `Monty::div_by_2_assign()` (with a blanket impl).
- Added `BoxedUint::inv_mod2k_vartime()`. 
- Made `BoxedUint::inv_mod2k()` public. 
- Added `Monty::Multiplier` associated type and `Monty::copy_montgomery_from()` to assist with tight loops (specifically, Lucas test in `crypto-primes`). 
- Cleaned up AMM, added comments and references, and reduced the size of the internal buffer to N from 2N. Also made it `const fn`. Closes #782
**Note:** the multiplier for `Uint` is called `DynMontyMultiplier`. Not happy with the name, but we already have `MontyMultiplier` as a trait, and it clashes.
**Note:** the exact way …
=> Monty-related performance improvements

src/traits.rs
Makes it easier to write generic code.
=> Bound `Monty` on `Retrieve`

benches/uint.rs, src/uint/rand.rs
In its current state, `random_bits_core` behaves differently on 32-bit and 64-bit targets in two ways:
1. The platforms order the randomly sampled bytes in a different order, generating different outputs.
2. For bit_length $\mod 64 \in [1, 32]$, the 64-bit platform samples four random bytes more than the 32-bit platform.
a.  this means the state of the RNG after calling this function is platform-dependent. This makes it impossible to use this function as an rng-seed-to-integer map.
This patch introduces:
- benchmarks to gauge the performance of the `random_bits_core` function,
- a patch to the `random_bits_core` function, and
- a test ensuring the `random_bits_core` output and rng state after calling it are platform-independent.
On my local machine, the function's performance remains …
=> Make `random_bits_core` platform independent

src/traits.rs, src/uint/boxed/ct.rs
Add an equivalent to `subtle`'s `ConditionallyNegate` trait without the `Copy` requirement.
=> impl `ConditionallyNegatable` for `BoxedUint`

src/int/div.rs, src/traits.rs, src/uint/boxed/div.rs, src/uint/div.rs
Expose the existing variable time division impls through a trait: `DivVartime`
Impl `DivVartime` for `Uint`, `BoxedUint` and `Int`.
=> Expose trait for variable time division 

src/traits.rs
Looks like the correct docs for `bit()` got misplaced.
=> Fix documentation of `BitOps::bit` method

src/int.rs, src/modular/boxed_monty_form/mul.rs, src/modular/safegcd/boxed.rs, src/uint.rs, src/uint/boxed.rs, src/uint/boxed/inv_mod.rs, src/uint/encoding.rs, src/uint/rand.rs
This better follows Rust conventions like `as_mut_slice`, where the ordering is like Rust's `mut T`.
The old names are retained, but deprecated.
=> Rename `as_(limbs|words)_mut` => `as_mut_(limbs|words)`

src/uint.rs, src/uint/boxed.rs, src/uint/ref_type.rs
Adds a reference newtype for a `Limb` slice which can be used as an abstraction for implementing shared functionality for both `Uint` and `BoxedUint`.
The initial implementation supports a limited amount of functionality but supports usage as both `&UintRef` and `&mut UintRef`.
This includes a common implementation of `fmt` impls shared between `Uint` and `BoxedUint`, replacing a copy-paste implementation.
Closes #756
=> Add `UintRef`

src/modular/boxed_monty_form.rs, src/modular/boxed_monty_form/add.rs, src/modular/boxed_monty_form/inv.rs, src/modular/boxed_monty_form/lincomb.rs, src/modular/boxed_monty_form/mul.rs, src/modular/boxed_monty_form/neg.rs, src/modular/boxed_monty_form/pow.rs, src/modular/boxed_monty_form/sub.rs
Fixes #804
Deref impl leaks the inner type. Should I make the conversion explicit instead?
=> Keep `BoxedMontyParams` in an `Arc`

src/modular/boxed_monty_form.rs, src/modular/safegcd/boxed.rs, src/odd.rs, src/traits.rs, src/uint/boxed.rs, src/uint/boxed/add.rs, src/uint/boxed/gcd.rs, src/uint/boxed/mul.rs, src/uint/boxed/sub.rs, tests/boxed_monty_form.rs, tests/boxed_uint.rs, tests/safegcd.rs
This PR attempts to simplify some scenarios that were encountered during the work on https://github.com/RustCrypto/RSA/pull/506.
- Instead of having `BoxedUint::shorten()`/`widen()` methods, introduce the `Resize` trait with more convenience methods. Implemented for `BoxedUint`, `NonZero<BoxedUint>`, `Odd<BoxedUint>`, and their references.
- `BoxedUint::shorten()` and `widen()` are marked as deprecated.
Note that `try_resize` fails if `self.bits() > at_least_bits_precision`, unlike the more relaxed `shorten()` behavior.
=> More convenience methods for boxed integer resizing

src/traits.rs
These changes will allow the trait to act as a drop-in replacement for the `Invert` trait in the `elliptic-curve` crate.
=> Remove `Invert` trait bounds and add default `invert_vartime`

src/modular/const_monty_form/macros.rs
This avoids the requirement to have it in scope
=> Have `impl_modulus!` reference itself by `$crate::`

.github/workflows/crypto-bigint.yml
Re-orders the CI config so linting steps are alphabetical, and adds a `test-*` prefix to anything which runs tests
=> CI: alphabetize lints and add `test-` prefix

.github/workflows/cargo-checkct.yml, checkct/driver/Cargo.toml
Hello @tarcieri :wave: 
This PR should fix your action. It'll still [fail](https://github.com/bboilot-ledger/crypto-bigint/actions/runs/15332758658/job/43143257617?pr=1) because the driver hasn't been implemented yet.
I am not a fan of the modification I had to do to the manifest in order for the tool to run. I'll discuss this matter with the team.
=> Fix cargo-checkct action

src/limb/mul.rs
This adjust the deprecation notice on `Limb::mac` to avoid confusion when upgrading crypto-bigint dependency.
=> adjust deprecation notice on mac

src/non_zero.rs, src/odd.rs
Make 
- `Odd::<Int>::abs() -> Odd<Uint>`, and 
- `NonZero::<Int>::abs() -> NonZero<Uint>`
instead of `-> Uint`.
=> Improve `Int::abs`

src/lib.rs, src/non_zero.rs, src/odd.rs
Adds the following type aliases:
- `NonZeroUint`
- `NonZeroBoxedUint`
- `OddUint`
- `OddBoxedUint`
This avoids consumers of the crate from having to assemble these themselves.
=> Add `NonZero` and `Odd` type aliases

src/non_zero.rs, src/odd.rs
Is there a reason #844 did not include these types? :smiley:
=> Add `NonZeroInt` and `OddInt` type aliases

src/const_choice.rs, src/int.rs, src/int/mul_uint.rs, src/int/resize.rs, src/uint.rs, src/uint/bingcd/extension.rs, src/uint/mul_int.rs
This PR introduces `Int::to_uint` and `Uint::to_int`, allowing better conversion between these types.
=> `Int`-`Uint` conversion

.github/workflows/crypto-bigint.yml, src/uint/bingcd.rs, src/uint/bingcd/gcd.rs
In their current form these tests take quite awhile to execute.
Adding `#[ignore]` omits them from typical test runs so the test suite still executes quickly.
The main `test` job in CI has been configured to run them with `--ignored`.
=> Add `#[ignore]` to bingcd tests

CHANGELOG.md
This cost me more than an hour of my life to debug. Let's add this to the change log right now, so we don't accidentally forget it in the 0.7.0 release
=> Mention `Uint::carrying_mul_add` interface change in `CHANGELOG.md`

.github/workflows/crypto-bigint.yml
Pins `clippy` to Rust 1.88, which prevents breaking the build when new lints are introduced in future Rust versions.
See also #859
=> CI: pin `clippy` version

src/modular/const_monty_form/macros.rs
Also adds a test it still works. It was broken in #861 (missing colon) when it was changed to invoke the new `const_monty_params!` macro.
Closes #865
=> Fix deprecated `impl_modulus!` macro

src/lib.rs
Helps make it more discoverable.
cc @fjarri
=> Mention `crypto-primes` in rustdoc

src/modular/const_monty_form.rs
The internal `from_integer` function is unnecessary because the only caller is `new`, so this gets rid of it and moves the function body to `new`.
=> ConstMontyForm: remove superfluous intermediate function

benches/monty.rs, src/modular.rs, src/modular/boxed_monty_form.rs, src/modular/const_monty_form.rs, src/modular/monty_form.rs, src/modular/shr1.rs, src/traits.rs, tests/boxed_monty_form.rs, tests/uint.rs
For a few reasons:
- It's more consistent with the existing uses of `shr1` in the codebase
- It's implemented in terms of `shr1` already
- With a little work it can be adapted into a full-fledged `shr`
This preserves the `div_by_2*` names with deprecations
=> Rename `div_by_2` to `shr1`

src/const_choice.rs
This improves error messages by reporting where `unwrap()`, `expect(msg)` was called rather than the assertion line in const_choice.rs.
=> Track caller when unwrapping ConstCtOption

src/modular/safegcd.rs, src/uint/invert_mod.rs
One last edge case I noticed in testing the Boxed implementation against num-bigint.
=> Fix edge case for Uint::invert_odd_mod with modulus 1

src/modular/boxed_monty_form.rs, src/modular/monty_form.rs
This could be used in reducing a 'wide' value through Montgomery reduction, but it isn't currently.
Removing this parameter has a strangely positive effect on the `monty` benchmarks (on my machine) which I don't really understand. Maybe just better register usage, or maybe the benchmarks are flawed.
```
Dynamic Montgomery arithmetic/double, U256
time:   [11.774 ns 12.594 ns 13.492 ns]
change: [−35.102% −30.294% −24.903%] (p = 0.00 < 0.05)
Dynamic Montgomery arithmetic/sub, U256
time:   [21.286 ns 21.676 ns 22.142 ns]
change: [−21.421% −13.981% −3.5879%] (p = 0.00 < 0.05)
Dynamic Montgomery arithmetic/neg, U256
time:   [11.440 ns 12.469 ns 13.556 ns]
change: [−40.821% −35.780% −29.448%] (p = 0.00 < 0.05)
```
=> Remove unused R3 from Montgomery parameters

src/modular/boxed_monty_form/invert.rs
Legacy of the `PrecomputeInverter` trait, which was removed in #894
=> Remove `BoxedMontyFormInverter`

src/modular.rs, src/modular/reduction.rs
It's an implementation detail. It was originally `pub` because it was used by the `const_monty_params!` nee `impl_modulus!` macro, however that has been changed to use `const fn` constructors instead.
=> Remove `modular::montgomery_reduction` from public API

benches/const_monty.rs, src/modular/const_monty_form/lincomb.rs
I'm unsure if I interpreted [this line](https://docs.rs/crypto-bigint/0.7.0-pre.7/crypto_bigint/modular/struct.ConstMontyForm.html#method.lincomb_vartime) correctly:
> This method is variable time only with the value of the modulus.
But it seems to me this is actually constant-time if the modulus is the same.
I'm not sure if this shouldn't actually apply to `MontyForm` and `BoxedMontyForm` as well. Because while they set their modulus during runtime, it still doesn't change between multiple calls to the same instantiation (AFAIU).
=> `ConstMontyForm::lincomb_vartime()` is constant-time

CHANGELOG.md, src/modular/const_monty_form.rs, src/modular/const_monty_form/reduce.rs, src/traits.rs
This trait comes from [`elliptic_curve::Reduce`](https://docs.rs/elliptic-curve/latest/elliptic_curve/ops/trait.Reduce.html). I thought this would fit better here as `cyrpto-bigint` already hosts a lot of [`modular`](https://docs.rs/crypto-bigint/latest/crypto_bigint/modular/index.html) arithmetic functionality.
Note that it slightly differs from `elliptic_curve::Reduce` because the input type is not bound by `Integer`, and there is no associated `Bytes` (and no `reduce_bytes` function). That is because `Reduce` can be implemented both on the input type and on `Bytes` as separate implementations, if the input type is not bounded by `Integer`.
=> Add `Reduce` trait for fixed modulus reduction.

src/modular/boxed_monty_form.rs, src/uint/boxed.rs, src/uint/boxed/div.rs, src/uint/boxed/shr.rs, tests/boxed_monty_form.rs, tests/boxed_uint.rs
Allowing mixed size inputs means that `rem` can be performed on 'wide' inputs without resizing the modulus, improving performance. The updated method can also be used to remove restrictions on `BoxedUint::mul_mod` but that's another update.
=> Update `BoxedUint::div_rem` to accept mixed sized inputs

src/modular.rs, src/modular/const_monty_form/invert.rs
Like #907, this is a vestige of the old safegcd implementation.
`ConstMontyForm::invert` now works for all sizes of limbs, so anyone needing to do `ConstMontyForm` inversion in a `const fn` context should just use that.
=> Remove `ConstMontyFormInverter`

src/modular/safegcd.rs
As noted in #905 this is the correct iteration count when `g ≤ f` is not ensured. There is no real impact on performance.
=> Fix iteration count for safegcd

src/limb.rs, src/uint/div.rs, src/uint/shl.rs, src/uint/shr.rs
This update adds internal `bounded_wrapping_sh(r/l)` and `wrapping_sh(r/l)_by_limbs` methods and optimizes `shr` and `shl` for `Uint` by applying sub-limb and super-limb shifts in different ways. Performance is generally improved (a lot), with division methods, `sqrt`, `bingcd`, and `MontyParams::new` also being particularly affected.
There is a variant of the bounded-wrapping shr method in `bingcd` which can be updated to use the new methods later.
=> Faster constant time bit shifts

benches/uint.rs, src/uint.rs, src/uint/bits.rs, src/uint/boxed.rs, src/uint/boxed/add_mod.rs, src/uint/boxed/bits.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs, src/uint/boxed/sqrt.rs, src/uint/encoding/der.rs, src/uint/ref_type.rs, src/uint/ref_type/bits.rs, src/uint/ref_type/shl.rs, src/uint/ref_type/shr.rs, src/uint/shl.rs, src/uint/shr.rs
This aligns `Uint` and `BoxedUint` bit operations by moving the logic to `UintRef` and removing the free functions.
=> Move bit operations to `UintRef`

benches/const_monty.rs, benches/uint.rs, src/const_choice.rs, src/int.rs, src/int/mod_symbol.rs, src/modular/bingcd/compact.rs, src/modular/bingcd/gcd.rs, src/modular/bingcd/xgcd.rs, src/modular/const_monty_form.rs, src/modular/const_monty_form/mod_symbol.rs, src/modular/monty_form.rs, src/modular/monty_form/mod_symbol.rs, src/traits.rs, src/uint.rs, src/uint/mod_symbol.rs, tests/common/mod.rs, tests/int.rs, tests/uint.rs
This implementation is based on `bingcd`. It does not appear to affect the GCD performance, being optimized away when it is not needed. This would be useful in `primefield` for adding `is_square`/`is_square_vartime` methods which should be faster than `sqrt`.
=> Add Jacobi symbol calculation

benches/uint.rs, src/uint.rs, src/uint/bits.rs, src/uint/boxed.rs, src/uint/boxed/add_mod.rs, src/uint/boxed/bits.rs, src/uint/boxed/shl.rs, src/uint/boxed/shr.rs, src/uint/boxed/sqrt.rs, src/uint/encoding/der.rs, src/uint/ref_type.rs, src/uint/ref_type/bits.rs, src/uint/ref_type/shl.rs, src/uint/ref_type/shr.rs, src/uint/shl.rs, src/uint/shr.rs, tests/boxed_monty_form.rs, tests/monty_form.rs
This fixes an issue with the carry value from `UintRef::shl1_assign` and extends the prop tests for `MontyForm` and `BoxedMontyForm`.
=> Re-apply "Move bit operations to UintRef (#920)"

src/int.rs, src/traits.rs, src/uint.rs, src/uint/boxed.rs
These are notably bounded on `Integer` and thus usable in place of `Integer` anywhere a signed or unsigned integer specifically is expected
I note there's TODOs to impl `Integer` and `FixedInteger` for `Int`. I went ahead and added another TODO to impl `Signed`.
=> Add `Signed` and `Unsigned` marker traits

Cargo.lock, Cargo.toml
Notably this release also enables the `const-generics` feature, which only incurs an MSRV bump to a much earlier version than our current MSRV so enabling it is more functionality for effectively free
=> Bump `hybrid-array` to v0.4.4; enable `subtle` feature

src/lib.rs
The former was removed from nightly. See RustCrypto/traits#2028
=> Switch from `doc_auto_cfg` to `doc_cfg`
